optaweb-tsp-planner/src/main/java/org/optaweb/tsp/optawebtspplanner/RouteMessage.java, optaweb-tsp-planner/src/main/java/org/optaweb/tsp/optawebtspplanner/TspMapController.java, optaweb-tsp-planner/src/main/java/org/optaweb/tsp/optawebtspplanner/TspPlannerComponent.java, optaweb-tsp-ui/src/App.js, optaweb-tsp-ui/src/LocationList.js
=> PLANNER-1274 Display route length and number of location

optaweb-tsp-ui/src/App.js
Useful resources:
- https://github.com/jmesnil/stomp-websocket/issues/81#issuecomment-311284871
Simple reconnection solution based on setTimeout(), some other
interesting ideas later in the discussion.
- https://github.com/JSteunou/webstomp-client
webstomp-client readme
- http://jmesnil.net/stomp-websocket/doc/
The original STOMP client documentation (webstomp-client is a fork of
stomp-websocket)
=> PLANNER-1275 Automatically reconnect after backend restart

optaweb-tsp-ui/src/components/TripData.tsx, optaweb-tsp-ui/src/registerServiceWorker.ts, optaweb-tsp-ui/src/setupTests.ts, optaweb-tsp-ui/tslint.json
https://palantir.github.io/tslint/rules/file-header/
=> Enforce license headers

README.adoc, optaweb-vehicle-routing-backend/README.adoc, optaweb-vehicle-routing-backend/pom.xml
* Initial getting started instructions done in 4fb1e14a214d1e3c0769f5931d198b98664f445f.
* Project structure improved and documented, Javadocs added in #44.
* This PR adds development guide for the backend.
=> PLANNER-1352: Development Guide

optaweb-vehicle-routing-backend/src/main/java/org/optaweb/vehiclerouting/plugin/persistence/LocationRepositoryImpl.java, optaweb-vehicle-routing-backend/src/main/java/org/optaweb/vehiclerouting/plugin/planner/RouteOptimizerConfig.java, optaweb-vehicle-routing-backend/src/main/java/org/optaweb/vehiclerouting/plugin/planner/RouteOptimizerImpl.java, optaweb-vehicle-routing-backend/src/main/java/org/optaweb/vehiclerouting/plugin/planner/RouterOptimizerImpl.java, optaweb-vehicle-routing-backend/src/main/java/org/optaweb/vehiclerouting/plugin/websocket/PortableLocation.java, optaweb-vehicle-routing-backend/src/main/java/org/optaweb/vehiclerouting/plugin/websocket/RoutePublisherImpl.java, optaweb-vehicle-routing-backend/src/main/java/org/optaweb/vehiclerouting/plugin/websocket/WebSocketController.java, optaweb-vehicle-routing-backend/src/main/java/org/optaweb/vehiclerouting/service/route/RouteListener.java, optaweb-vehicle-routing-backend/src/test/java/org/optaweb/vehiclerouting/plugin/persistence/LocationRepositoryImplTest.java, optaweb-vehicle-routing-backend/src/test/java/org/optaweb/vehiclerouting/plugin/planner/RouteOptimizerImplTest.java, optaweb-vehicle-routing-backend/src/test/java/org/optaweb/vehiclerouting/plugin/websocket/PortableLocationTest.java, optaweb-vehicle-routing-backend/src/test/java/org/optaweb/vehiclerouting/plugin/websocket/RoutePublisherImplTest.java, optaweb-vehicle-routing-backend/src/test/java/org/optaweb/vehiclerouting/plugin/websocket/WebSocketControllerTest.java, optaweb-vehicle-routing-backend/src/test/java/org/optaweb/vehiclerouting/service/location/LocationServiceTest.java, optaweb-vehicle-routing-backend/src/test/java/org/optaweb/vehiclerouting/service/route/RouteListenerTest.java
=> Basic test coverage

optaweb-vehicle-routing-frontend/package-lock.json, optaweb-vehicle-routing-frontend/package.json, optaweb-vehicle-routing-frontend/src/@types/leaflet-geosearch.d.ts, optaweb-vehicle-routing-frontend/src/components/LocationList.test.tsx, optaweb-vehicle-routing-frontend/src/components/LocationList.tsx, optaweb-vehicle-routing-frontend/src/components/SearchBox.test.tsx, optaweb-vehicle-routing-frontend/src/components/SearchBox.tsx, optaweb-vehicle-routing-frontend/src/components/TravelingSalesmanProblem.tsx, optaweb-vehicle-routing-frontend/src/components/__snapshots__/LocationList.test.tsx.snap, optaweb-vehicle-routing-frontend/src/components/__snapshots__/SearchBox.test.tsx.snap, optaweb-vehicle-routing-frontend/tsconfig.json
This is the quickest solution to get basic geosearch feature. I'm using [Leaflet.GeoSearch](https://github.com/smeijer/leaflet-geosearch) React component with built-in `OpenStreetMapProvider` that queries public [Nominatim](https://wiki.openstreetmap.org/wiki/Nominatim) service. It has restrictive usage policy but there are 3rd party providers of the same API and we can set up our own instance.
Leaflet.GeoSearch has other built-in providers for Bind, Esri, Google Maps, and Nominatim-based services LocationIQ and OpenCage. It also has a Leaflet look-and-feel control but we're going to use a custom Patternfly based control (something along the lines of what's part of this PR).
Patternfly doesn't seem to have a generic search control with auto-suggestion but I have emulated it quite easily …
=> PLANNER-1272: Geocoding proof of concept

optaweb-vehicle-routing-frontend/README.adoc
Should help to detect out-of-date dependencies early.
=> Add dependencies badges

optaweb-vehicle-routing-backend/pom.xml
https://nvd.nist.gov/vuln/detail/CVE-2019-12086
Thanks GitHub for the alert!
=> Upgrade jackson-databind to avoid CVE-2019-12086

optaweb-vehicle-routing-backend/pom.xml
https://nvd.nist.gov/vuln/detail/CVE-2019-12814
Thanks GitHub for the alert!
=> Upgrade jackson-databind to avoid CVE-2019-12814

optaweb-vehicle-routing-backend/pom.xml
"mvn clean package" now produces a fat jar again.
=> Declare spring boot repackage goal to build a fat jar

optaweb-vehicle-routing-backend/src/main/java/org/optaweb/vehiclerouting/plugin/planner/change/ChangeVehicleCapacity.java, optaweb-vehicle-routing-backend/src/main/java/org/optaweb/vehiclerouting/plugin/planner/change/RemoveLocation.java, optaweb-vehicle-routing-backend/src/main/java/org/optaweb/vehiclerouting/plugin/planner/change/RemoveVehicle.java, optaweb-vehicle-routing-backend/src/main/java/org/optaweb/vehiclerouting/plugin/planner/change/RemoveVisit.java
Planning entity collections are cloned automatically by solution cloner.
=> Do not clone vehicleList, it's a planning entity collection

README.adoc
Signed-off-by: Mikhail Ramendik <mramendi@redhat.com>
=> [BXMSDOC-4565] Misha's edit to README.adoc - added usage

optaweb-vehicle-routing-frontend/package-lock.json, optaweb-vehicle-routing-frontend/package.json
To unify test result format due to internal tooling.
=> BAQE-1008 Report frontend tests results in junit format

pom.xml
- https://nvd.nist.gov/vuln/detail/CVE-2019-14540
- https://nvd.nist.gov/vuln/detail/CVE-2019-16335
Thanks GitHub for the alert!
=> Upgrade jackson-databind to avoid CVE-2019-14540,16335

optaweb-vehicle-routing-frontend/.eslintrc.json, optaweb-vehicle-routing-frontend/src/ui/App.tsx, optaweb-vehicle-routing-frontend/src/ui/components/Location.tsx, optaweb-vehicle-routing-frontend/src/ui/components/Vehicle.tsx, optaweb-vehicle-routing-frontend/src/ui/connection/ConnectionError.tsx, optaweb-vehicle-routing-frontend/src/ui/header/Toolbar.tsx, optaweb-vehicle-routing-frontend/src/ui/pages/Demo.tsx, optaweb-vehicle-routing-frontend/src/ui/pages/Route.tsx, optaweb-vehicle-routing-frontend/src/ui/pages/Vehicles.tsx
Airbnb style: Omit the value of the prop when it is explicitly true.
https://airbnb.io/javascript/react/
=> Fix eslint config (s/on/error/), don't override react/jsx-boolean-value

optaweb-vehicle-routing-backend/src/main/java/org/optaweb/vehiclerouting/plugin/planner/RouteOptimizerConfig.java, optaweb-vehicle-routing-backend/src/test/java/org/optaweb/vehiclerouting/plugin/planner/SolverIntegrationTest.java
Depends on kiegroup/optaplanner#589.
=> Upgrade to the new API for creating SolverConfig

optaweb-vehicle-routing-frontend/pom.xml
=> BXMSPROD-560 lock-treatment-tool added to productized profile

optaweb-vehicle-routing-backend/pom.xml, optaweb-vehicle-routing-distribution/pom.xml, optaweb-vehicle-routing-frontend/pom.xml, pom.xml
Now it's identical to the example at https://maven.apache.org/pom.html and to what IDEA generates when new module is added.
Also replacing the old XSD URL with a new one.
=> Unify POMs

.travis.yml, optaweb-vehicle-routing-frontend/pom.xml
=> BXMSPROD-560 lock-treatment-tool execution moved to defult profile

optaweb-vehicle-routing-frontend/pom.xml
@Ginxo I think you intended to do this in #218 but it probably disappeared when you merged master to your PR branch.
=> BXMSPROD-560 Remove productizedProfile with lock-treatment-tool

optaweb-vehicle-routing-frontend/package-lock.json, optaweb-vehicle-routing-frontend/package.json, optaweb-vehicle-routing-frontend/pom.xml
BXMSPROD-597
* lock-treatment-tool added to dev-dependencies
* locktt script added
* pom execution changed to npm run locktt
=> BXMSPROD-597: frontend project locktt execution improved

optaweb-vehicle-routing-frontend/pom.xml
=> BXMSPROD-580: frontend-maven-plugin version pointing to the centralised one

optaweb-vehicle-routing-backend/pom.xml, pom.xml
Depends on https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1086
=> Remove Spring Boot dependency management

pom.xml
Depends on https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1100
=> Remove AssertJ dependency version

pom.xml
Depends on https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1130
=> Remove Neovisionaries dependency management

optaweb-vehicle-routing-backend/src/main/resources/application.properties
Replicates https://github.com/kiegroup/optaweb-employee-rostering/pull/368.
=> Allow PostgreSQL database host to be specfied

optaweb-vehicle-routing-docs/pom.xml
https://issues.redhat.com/browse/PLANNER-1839
- kiegroup/droolsjbpm-build-bootstrap/pull/1192
- kiegroup/kie-docs/pull/2200 (optional)
- kiegroup/optaplanner/pull/696
- kiegroup/optaweb-employee-rostering/pull/395
- kiegroup/optaweb-vehicle-routing/pull/268
=> PLANNER-1839: Have Asciidoctor managed by kie-parent

optaweb-vehicle-routing-backend/pom.xml
Merge with:
https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1196
https://github.com/kiegroup/optaplanner/pull/701
https://github.com/kiegroup/jbpm-work-items/pull/124
https://github.com/kiegroup/optaweb-employee-rostering/pull/397
=> [7.33.x] RHPAM-2734: Minor fixes for downgrade to Spring Boot 2.1.12

optaweb-vehicle-routing-backend/src/main/java/org/optaweb/vehiclerouting/plugin/planner/RouteOptimizerConfig.java, optaweb-vehicle-routing-backend/src/main/resources/application.properties
Depends on kiegroup/optaplanner/pull/723.
=> PLANNER-1907: Enable daemon mode in application.properties

optaweb-vehicle-routing-backend/pom.xml
Depends on kiegroup/droolsjbpm-build-bootstrap/pull/1263.
=> PLANNER-1912,RHPAM-2800: Make backend pom.xml valid

optaweb-vehicle-routing-backend/pom.xml
=> [7.33.x] PLANNER-1912,RHPAM-2800: Make backend pom.xml valid (#290)

.gitignore, README.adoc, optaweb-vehicle-routing-docs/src/main/asciidoc/index.adoc, optaweb-vehicle-routing-docs/src/main/asciidoc/run-locally.adoc, runLocally.sh
=> PLANNER-1718: Add runLocally.sh script

optaweb-vehicle-routing-backend/src/main/java/org/optaweb/vehiclerouting/plugin/planner/VehicleRoutingConstraintProvider.java, optaweb-vehicle-routing-backend/src/main/java/org/optaweb/vehiclerouting/plugin/planner/change/AddVehicle.java, optaweb-vehicle-routing-backend/src/main/java/org/optaweb/vehiclerouting/plugin/planner/change/AddVisit.java, optaweb-vehicle-routing-backend/src/main/java/org/optaweb/vehiclerouting/plugin/planner/domain/PlanningLocation.java, optaweb-vehicle-routing-backend/src/main/java/org/optaweb/vehiclerouting/plugin/planner/domain/PlanningVehicle.java, optaweb-vehicle-routing-backend/src/main/java/org/optaweb/vehiclerouting/plugin/planner/domain/PlanningVisit.java, optaweb-vehicle-routing-backend/src/main/java/org/optaweb/vehiclerouting/plugin/planner/domain/Standstill.java, optaweb-vehicle-routing-backend/src/main/java/org/optaweb/vehiclerouting/plugin/planner/domain/VehicleRoutingSolution.java, optaweb-vehicle-routing-backend/src/main/java/org/optaweb/vehiclerouting/plugin/planner/weight/DepotAngleVisitDifficultyWeightFactory.java, optaweb-vehicle-routing-backend/src/test/java/org/optaweb/vehiclerouting/plugin/planner/RouteOptimizerImplTest.java, optaweb-vehicle-routing-backend/src/test/java/org/optaweb/vehiclerouting/plugin/planner/SolverManagerTest.java, optaweb-vehicle-routing-backend/src/test/java/org/optaweb/vehiclerouting/plugin/planner/change/AddVehicleTest.java, optaweb-vehicle-routing-backend/src/test/java/org/optaweb/vehiclerouting/plugin/planner/change/ChangeVehicleCapacityTest.java, optaweb-vehicle-routing-backend/src/test/java/org/optaweb/vehiclerouting/plugin/planner/change/RemoveVehicleTest.java, optaweb-vehicle-routing-backend/src/test/java/org/optaweb/vehiclerouting/plugin/planner/domain/PlanningLocationFactoryTest.java, optaweb-vehicle-routing-backend/src/test/java/org/optaweb/vehiclerouting/plugin/planner/domain/PlanningLocationTest.java
Small changes, see commit messages.
=> Clean up planning domain 3

optaweb-vehicle-routing-frontend/package-lock.json, optaweb-vehicle-routing-frontend/package.json, optaweb-vehicle-routing-frontend/src/ui/__snapshots__/App.test.tsx.snap, optaweb-vehicle-routing-frontend/src/ui/components/DemoDropdown.tsx, optaweb-vehicle-routing-frontend/src/ui/components/__snapshots__/DemoDropdown.test.tsx.snap, optaweb-vehicle-routing-frontend/src/ui/components/__snapshots__/Location.test.tsx.snap, optaweb-vehicle-routing-frontend/src/ui/components/__snapshots__/LocationList.test.tsx.snap, optaweb-vehicle-routing-frontend/src/ui/components/__snapshots__/SearchBox.test.tsx.snap, optaweb-vehicle-routing-frontend/src/ui/components/__snapshots__/UnderConstruction.test.tsx.snap, optaweb-vehicle-routing-frontend/src/ui/components/__snapshots__/Vehicle.test.tsx.snap, optaweb-vehicle-routing-frontend/src/ui/connection/__snapshots__/ConnectionError.test.tsx.snap, optaweb-vehicle-routing-frontend/src/ui/header/__snapshots__/Header.test.tsx.snap, optaweb-vehicle-routing-frontend/src/ui/header/__snapshots__/Navigation.test.tsx.snap, optaweb-vehicle-routing-frontend/src/ui/header/__snapshots__/Toolbar.test.tsx.snap, optaweb-vehicle-routing-frontend/src/ui/pages/__snapshots__/Demo.test.tsx.snap, optaweb-vehicle-routing-frontend/src/ui/pages/__snapshots__/Route.test.tsx.snap, optaweb-vehicle-routing-frontend/src/ui/pages/__snapshots__/Vehicles.test.tsx.snap
It looks like a more recent version of Typescript is required, so this
also updates Typescript to the latest version available.
CRA gives a warning using this version of Typescript tho:
```
Creating an optimized production build...
=============
WARNING: You are currently running a version of TypeScript which is not officially supported by typescript-estree.
You may find that it works just fine, or you may not.
SUPPORTED TYPESCRIPT VERSIONS: >=3.2.1 <3.5.0
YOUR TYPESCRIPT VERSION: 3.8.3
Please only submit bug reports when using the officially supported version.
=============
```
AFAIK it's benign and can be ignored, but it would be a good idea to
update CRA too.
=> PLANNER-1946: Upgrade to the latest @patternfly/react-core

.travis.yml, optaweb-vehicle-routing-frontend/pom.xml
Unify `npm install` related task under the `initialize` phase.
=>  Move npm install to Maven's initialize phase 

pom.xml
=> Remove override of jackson-dataformat-yaml version

optaweb-vehicle-routing-backend/src/main/java/org/optaweb/vehiclerouting/plugin/persistence/LocationEntity.java, optaweb-vehicle-routing-backend/src/main/java/org/optaweb/vehiclerouting/plugin/persistence/LocationRepositoryImpl.java, optaweb-vehicle-routing-backend/src/test/java/org/optaweb/vehiclerouting/plugin/persistence/DistanceRepositoryImplTest.java, optaweb-vehicle-routing-backend/src/test/java/org/optaweb/vehiclerouting/plugin/persistence/LocationEntityTest.java, optaweb-vehicle-routing-backend/src/test/java/org/optaweb/vehiclerouting/plugin/persistence/LocationRepositoryImplTest.java, optaweb-vehicle-routing-backend/src/test/java/org/optaweb/vehiclerouting/plugin/persistence/LocationRepositoryIntegrationTest.java, optaweb-vehicle-routing-backend/src/test/java/org/optaweb/vehiclerouting/plugin/persistence/VehicleRepositoryImplTest.java, optaweb-vehicle-routing-backend/src/test/java/org/optaweb/vehiclerouting/plugin/planner/RouteOptimizerImplTest.java, optaweb-vehicle-routing-backend/src/test/java/org/optaweb/vehiclerouting/plugin/planner/SolverExceptionTest.java, optaweb-vehicle-routing-backend/src/test/java/org/optaweb/vehiclerouting/plugin/planner/SolverManagerTest.java
Mocking value objects is an anti-pattern (`Ctrl-F value object` at https://javadoc.io/static/org.mockito/mockito-core/3.3.3/org/mockito/Mockito.html). Also see this [SO discussion](https://stackoverflow.com/questions/47304193/don-t-mock-value-objects-too-generic-rule-without-explanation).
Closes #116.
=> Reduce mocking

optaweb-vehicle-routing-frontend/package-lock.json
- https://www.npmjs.com/advisories/1179
- https://www.npmjs.com/advisories/1486
- https://www.npmjs.com/advisories/1500
=> Upgrade npm dependencies to fix vulnerabilities

pom.xml
Merge with: https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1350
=> Manage postgresql version with kie-parent

optaweb-vehicle-routing-backend/src/main/java/org/optaweb/vehiclerouting/domain/Coordinates.java, optaweb-vehicle-routing-backend/src/main/java/org/optaweb/vehiclerouting/domain/Distance.java, optaweb-vehicle-routing-backend/src/main/java/org/optaweb/vehiclerouting/domain/Location.java, optaweb-vehicle-routing-backend/src/main/java/org/optaweb/vehiclerouting/domain/Vehicle.java, optaweb-vehicle-routing-backend/src/test/java/org/optaweb/vehiclerouting/domain/CoordinatesTest.java, optaweb-vehicle-routing-backend/src/test/java/org/optaweb/vehiclerouting/domain/DistanceTest.java, optaweb-vehicle-routing-backend/src/test/java/org/optaweb/vehiclerouting/domain/LocationDataTest.java, optaweb-vehicle-routing-backend/src/test/java/org/optaweb/vehiclerouting/domain/LocationTest.java, optaweb-vehicle-routing-backend/src/test/java/org/optaweb/vehiclerouting/domain/VehicleDataTest.java, optaweb-vehicle-routing-backend/src/test/java/org/optaweb/vehiclerouting/domain/VehicleTest.java, optaweb-vehicle-routing-backend/src/test/java/org/optaweb/vehiclerouting/plugin/persistence/DistanceEntityTest.java, optaweb-vehicle-routing-backend/src/test/java/org/optaweb/vehiclerouting/plugin/planner/domain/PlanningVehicleTest.java, optaweb-vehicle-routing-backend/src/test/java/org/optaweb/vehiclerouting/plugin/planner/weight/DepotAngleVisitDifficultyWeightFactoryTest.java, optaweb-vehicle-routing-backend/src/test/java/org/optaweb/vehiclerouting/plugin/websocket/PortableCoordinatesTest.java, optaweb-vehicle-routing-backend/src/test/java/org/optaweb/vehiclerouting/plugin/websocket/PortableDistanceTest.java, optaweb-vehicle-routing-backend/src/test/java/org/optaweb/vehiclerouting/plugin/websocket/PortableErrorMessageTest.java, optaweb-vehicle-routing-backend/src/test/java/org/optaweb/vehiclerouting/plugin/websocket/PortableLocationTest.java, optaweb-vehicle-routing-backend/src/test/java/org/optaweb/vehiclerouting/plugin/websocket/PortableVehicleTest.java
SonarCloud started detecting these recently.
Fixing.
=> Fix assertion code smells

optaweb-vehicle-routing-backend/src/test/java/org/optaweb/vehiclerouting/domain/RouteTest.java, optaweb-vehicle-routing-backend/src/test/java/org/optaweb/vehiclerouting/domain/RouteWithTrackTest.java, optaweb-vehicle-routing-backend/src/test/java/org/optaweb/vehiclerouting/domain/RoutingPlanTest.java, optaweb-vehicle-routing-backend/src/test/java/org/optaweb/vehiclerouting/plugin/planner/SolverManagerTest.java, optaweb-vehicle-routing-backend/src/test/java/org/optaweb/vehiclerouting/plugin/routing/GraphHopperRouterTest.java
SonarCloud started reporting this recently.
=> Reduce invocations in lambdas supposed to throw an exception

runOnOpenShift.sh
Made runOnOpenShift.sh to store configurations
into Deployments instead of DeploymentsConfig
=> Change configuration to new OCP 4.5.1 standart

optaweb-vehicle-routing-backend/src/main/java/org/optaweb/vehiclerouting/plugin/persistence/DistanceCrudRepository.java, optaweb-vehicle-routing-backend/src/main/java/org/optaweb/vehiclerouting/plugin/persistence/DistanceRepositoryImpl.java, optaweb-vehicle-routing-backend/src/main/java/org/optaweb/vehiclerouting/plugin/routing/GraphHopperRouter.java, optaweb-vehicle-routing-backend/src/main/java/org/optaweb/vehiclerouting/service/distance/DistanceCalculationException.java, optaweb-vehicle-routing-backend/src/main/java/org/optaweb/vehiclerouting/service/distance/DistanceCalculator.java, optaweb-vehicle-routing-backend/src/main/java/org/optaweb/vehiclerouting/service/distance/DistanceMatrixImpl.java, optaweb-vehicle-routing-backend/src/main/java/org/optaweb/vehiclerouting/service/distance/DistanceRepository.java, optaweb-vehicle-routing-backend/src/main/java/org/optaweb/vehiclerouting/service/location/LocationService.java, optaweb-vehicle-routing-backend/src/test/java/org/optaweb/vehiclerouting/plugin/persistence/DistanceRepositoryImplTest.java, optaweb-vehicle-routing-backend/src/test/java/org/optaweb/vehiclerouting/plugin/persistence/DistanceRepositoryIntegrationTest.java, optaweb-vehicle-routing-backend/src/test/java/org/optaweb/vehiclerouting/service/distance/DistanceMatrixImplTest.java, optaweb-vehicle-routing-backend/src/test/java/org/optaweb/vehiclerouting/service/location/LocationServiceTest.java
https://issues.redhat.com/browse/PLANNER-2067
Also fixes #83.
=> PLANNER-2067: Remove location's distance from the matrix

Jenkinsfile
https://issues.redhat.com/browse/PLANNER-2202
<details>
<summary>
</summary>
</details>
=> PLANNER-2202 Create PR pipelines for Optawebs

.github/workflows/pull_request.yml
<details>
<summary>
</summary>
</details>
=> pull request flow updated to use github-action-build-chain@v2.1

optaweb-vehicle-routing-backend/pom.xml
<details>
<summary>
</summary>
</details>
=> Remove obsolete comment about sonarcloud

.travis.yml
https://sonarcloud.io/documentation/appendices/move-analysis-node-js-10/
<details>
<summary>
</summary>
</details>
=> Set Node.js version to LTS in Travis config

optaweb-vehicle-routing-backend/pom.xml, optaweb-vehicle-routing-distribution/pom.xml, optaweb-vehicle-routing-docs/pom.xml, optaweb-vehicle-routing-frontend/pom.xml, optaweb-vehicle-routing-standalone/pom.xml, pom.xml
https://issues.redhat.com/browse/PLANNER-2243
https://github.com/kiegroup/optaplanner/pull/1023
https://github.com/kiegroup/optaplanner-quickstarts/pull/21
<details>
<summary>
</summary>
</details>
=> PLANNER-2243 Upgrade project version to 8.1.0-SNAPSHOT

.github/workflows/pull_request.yml
<details>
<summary>
</summary>
</details>
=> fix master pull request flow

build/release/upload_distribution.sh
Tested locally and results verified via FileZilla on the remote server.
https://issues.redhat.com/browse/PLANNER-2216
A similar script for Employee Rostering: https://github.com/kiegroup/optaweb-employee-rostering/pull/526
<details>
<summary>
</summary>
</details>
=> PLANNER-2216 Create a distribution upload script

.github/workflows/pull_request.yml
https://issues.redhat.com/browse/BXMSPROD-1062
related PRs:
* https://github.com/kiegroup/kie-soup/pull/164
* https://github.com/kiegroup/droolsjbpm-knowledge/pull/483
* https://github.com/kiegroup/drools/pull/3216
* https://github.com/kiegroup/optaplanner/pull/1013
* https://github.com/kiegroup/jbpm/pull/1795
* https://github.com/kiegroup/kie-jpmml-integration/pull/47
* https://github.com/kiegroup/droolsjbpm-integration/pull/2309
* https://github.com/kiegroup/openshift-drools-hacep/pull/104
* https://github.com/kiegroup/droolsjbpm-tools/pull/123
* https://github.com/kiegroup/lienzo-core/pull/139
* https://github.com/kiegroup/lienzo-tests/pull/112
* https://github.com/kiegroup/appformer/pull/1074
* https://github.com/kiegroup/kie-uberfire-extensions/pull/110
* …
=> [7.x] BXMSPROD-1062 kiegroup/github-action-build-chain updated

optaweb-vehicle-routing-backend/pom.xml, optaweb-vehicle-routing-distribution/pom.xml, optaweb-vehicle-routing-docs/pom.xml, optaweb-vehicle-routing-frontend/pom.xml, optaweb-vehicle-routing-standalone/pom.xml, pom.xml
https://issues.redhat.com/browse/PLANNER-2243
<details>
<summary>
</summary>
</details>
=> PLANNER-2243 Release version 8.0.0.Final

optaweb-vehicle-routing-backend/pom.xml, optaweb-vehicle-routing-distribution/pom.xml, optaweb-vehicle-routing-docs/pom.xml, optaweb-vehicle-routing-frontend/pom.xml, optaweb-vehicle-routing-standalone/pom.xml, pom.xml
Due to branch 8.1.x created
Related PRs:
- https://github.com/kiegroup/optaplanner/pull/1073
- https://github.com/kiegroup/optaweb-vehicle-routing/pull/412
- https://github.com/kiegroup/optaweb-employee-rostering/pull/547
- https://github.com/kiegroup/optaplanner-quickstarts/pull/37
=> Updated version to 8.2.0-SNAPSHOT

README.adoc
<details>
<summary>
</summary>
</details>
=> Add getting started video to Readme

optaweb-vehicle-routing-backend/pom.xml, optaweb-vehicle-routing-distribution/pom.xml, optaweb-vehicle-routing-docs/pom.xml, optaweb-vehicle-routing-frontend/pom.xml, optaweb-vehicle-routing-standalone/pom.xml, pom.xml
https://github.com/kiegroup/optaplanner/pull/1120
https://github.com/kiegroup/optaplanner-quickstarts/pull/47
https://github.com/kiegroup/optaweb-vehicle-routing/pull/418
https://github.com/kiegroup/optaweb-employee-rostering/pull/554
https://github.com/kiegroup/kogito-examples/pull/537
https://github.com/kiegroup/kogito-apps/pull/612
<details>
<summary>
</summary>
* for an <b>upstream build</b> …
=> Upgrade version to 8.3.0-SNAPSHOT

.github/workflows/pull_request.yml
https://issues.redhat.com/browse/BXMSPROD-1202
- https://github.com/kiegroup/optaweb-employee-rostering/pull/560
- https://github.com/kiegroup/optaweb-vehicle-routing/pull/421
- https://github.com/kiegroup/kie-wb-distributions/pull/1083
- https://github.com/kiegroup/droolsjbpm-integration/pull/2392
- https://github.com/kiegroup/optaweb-employee-rostering/pull/561
- https://github.com/kiegroup/optaweb-vehicle-routing/pull/422
<details>
<summary>
</summary>
* for a <b>full production downstream …
=> BXMSPROD-1202 ubuntu-latest to ubuntu-18.04 (master)

.github/workflows/pull_request.yml
https://issues.redhat.com/browse/BXMSPROD-1202
- https://github.com/kiegroup/optaweb-employee-rostering/pull/560
- https://github.com/kiegroup/optaweb-vehicle-routing/pull/421
- https://github.com/kiegroup/kie-wb-distributions/pull/1083
- https://github.com/kiegroup/droolsjbpm-integration/pull/2392
- https://github.com/kiegroup/optaweb-employee-rostering/pull/561
- https://github.com/kiegroup/optaweb-vehicle-routing/pull/422
<details>
<summary>
</summary>
* for a <b>full production downstream …
=> BXMSPROD-1202 ubuntu-latest to ubuntu-18.04 (7.x)

.github/workflows/pull_request.yml, .mvn/extensions.xml
https://issues.redhat.com/browse/BXMSPROD-1216
- https://github.com/kiegroup/optaweb-vehicle-routing/pull/438
- https://github.com/kiegroup/optaweb-employee-rostering/pull/580
=> BXMSPROD-1216 .mvn/extensions.xml takari (master)

optaweb-vehicle-routing-standalone/pom.xml
The same fix as here:
https://github.com/kiegroup/optaweb-employee-rostering/pull/587
=> Configure docker to run as non-root user

optaweb-vehicle-routing-docs/src/main/asciidoc/appendix-backend-architecture.adoc, optaweb-vehicle-routing-docs/src/main/asciidoc/development-guide.adoc, optaweb-vehicle-routing-docs/src/main/asciidoc/run-locally.adoc, optaweb-vehicle-routing-docs/src/main/asciidoc/run-noscript.adoc
<details>
<summary>
</summary>
</details>
=> Update docs to Quarkus

optaweb-vehicle-routing-docs/src/main/asciidoc/development-guide.adoc
Follows up on #456.
<details>
<summary>
</summary>
</details>
=> Minor documentation fixes

optaweb-vehicle-routing-backend/.gitignore
<details>
<summary>
</summary>
</details>
=> Ignore Panache archive marker

runLocally.sh, runOnOpenShift.sh
https://issues.redhat.com/browse/PLANNER-2036
Fixes #320.
<details>
<summary>
</summary>
</details>
=> PLANNER-2036: Port runLocally.sh VRP to work on macOS

optaweb-vehicle-routing-distribution/src/main/assembly/assembly-optaweb-vehicle-routing.xml
<details>
<summary>
</summary>
</details>
=> Add readme and lincese to distribution root

runLocally.sh
This allows for example to change HTTP port: `./runLocally.sh spain -Dquarkus.http.port=9090`.
<details>
<summary>
</summary>
</details>
=> Pass extra arguments from runLocally.sh to java

.github/workflows/pull_request.yml
https://issues.redhat.com/browse/BXMSPROD-1311
Related pull requests:
* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1641
* https://github.com/kiegroup/kie-soup/pull/202
* https://github.com/kiegroup/droolsjbpm-knowledge/pull/519
* https://github.com/kiegroup/drools/pull/3599
* https://github.com/kiegroup/optaplanner/pull/1314
* https://github.com/kiegroup/lienzo-core/pull/144
* https://github.com/kiegroup/lienzo-tests/pull/116
* https://github.com/kiegroup/appformer/pull/1139
* https://github.com/kiegroup/kie-uberfire-extensions/pull/114
* https://github.com/kiegroup/jbpm/pull/1928
* https://github.com/kiegroup/kie-jpmml-integration/pull/53
* https://github.com/kiegroup/droolsjbpm-integration/pull/2476
* https://github.com/kiegroup/kie-wb-playground/pull/106
* …
=> BXMSPROD-1311 action-surefire-report

optaweb-vehicle-routing-frontend/src/store/route/route.test.ts, optaweb-vehicle-routing-frontend/src/store/route/selectors.ts, optaweb-vehicle-routing-frontend/src/ui/pages/Demo.test.tsx, optaweb-vehicle-routing-frontend/src/ui/pages/Demo.tsx, optaweb-vehicle-routing-frontend/src/ui/pages/InfoBlock.test.tsx, optaweb-vehicle-routing-frontend/src/ui/pages/InfoBlock.tsx, optaweb-vehicle-routing-frontend/src/ui/pages/__snapshots__/Demo.test.tsx.snap, optaweb-vehicle-routing-frontend/src/ui/pages/__snapshots__/InfoBlock.test.tsx.snap
https://issues.redhat.com/browse/PLANNER-2421
<details>
<summary>
</summary>
</details>
=> PLANNER-2421: Show capacity usage

optaweb-vehicle-routing-backend/src/main/java/org/optaweb/vehiclerouting/plugin/routing/RoutingConfig.java
Improve getting started experience.
People sometimes run into a situation where the OSM import fails (`.osm.pbf` file too large and not enough JVM memory to import it). In that case `~/.optaweb-vehicle-routing/graphhopper/<region>/` is created but it remains empty.
Previously, we only checked whether the directory existed in which case we tried to _load_ the graph and GraphHopper would fail.
Now we also check if the graph dir is empty, in which case we take the _import_ branch.
<details>
<summary>
</summary>
* for a <b>compile downstream build</b> please add comment: <b>Jenkins …
=> Do not fail if the graph directory is empty

optaweb-vehicle-routing-backend/src/test/java/org/optaweb/vehiclerouting/plugin/planner/SolverIntegrationTest.java
(cherry picked from commit 5da4c4439935a1db38e2c909289103d7140d08f5)
The test is not flaky in a non-deterministic manner. The 1s timout just
became insufficient when Drools introduced the Alpha Network Compiler.
https://blog.kie.org/2021/04/demystifying-the-alpha-network-compiler-anc.html
What seems to be happening is that the first problem fact change
triggers Alpha Network compilation, which makes constraint evaluation
faster at the cost of taking some performance in the initial phase.
This makes the original timeout for PFC completion insuffcient.
#496
<details>
<summary>
</summary>
* for a <b>full downstream build</b> please add comment: <b>Jenkins run …
=> Increase timeout in a test

optaweb-vehicle-routing-backend/src/main/java/org/optaweb/vehiclerouting/service/demo/RoutingProblemConfig.java, optaweb-vehicle-routing-backend/src/main/java/org/optaweb/vehiclerouting/service/demo/RoutingProblemList.java, optaweb-vehicle-routing-backend/src/test/java/org/optaweb/vehiclerouting/service/demo/RoutingProblemListTest.java
Just an occasional code cleanup.
<details>
<summary>
</summary>
</details>
=> Streamify collecting of problems

optaweb-vehicle-routing-backend/src/test/java/org/optaweb/vehiclerouting/service/demo/RoutingProblemListTest.java
<details>
<summary>
</summary>
</details>
=> Add missing negative test

.github/workflows/pull_request.yml
https://issues.redhat.com/browse/BXMSPROD-1390
- https://github.com/kiegroup/optaweb-vehicle-routing/pull/519
- https://github.com/kiegroup/optaweb-employee-rostering/pull/645
<details>
<summary>
</summary>
</details>
=> [master] BXMSPROD-1390 github actions flows concurrency

.github/workflows/pull_request.yml, CONTRIBUTING.adoc, README.adoc, optaweb-vehicle-routing-docs/src/main/asciidoc/development-guide.adoc
**PLEASE DO NOT MERGE. THIS WILL BE DONE WHEN `master` will be renamed as `main`**
Related PRs:
- https://github.com/kiegroup/kogito-pipelines/pull/188
- https://github.com/kiegroup/kogito-runtimes/pull/1365
- https://github.com/kiegroup/optaplanner/pull/1372
- https://github.com/kiegroup/optaweb-employee-rostering/pull/660
- https://github.com/kiegroup/optaweb-vehicle-routing/pull/532
- https://github.com/kiegroup/optaplanner-quickstarts/pull/144
- https://github.com/kiegroup/kogito-apps/pull/882
- https://github.com/kiegroup/kogito-examples/pull/729
- https://github.com/kiegroup/kogito-images/pull/516
- https://github.com/kiegroup/kogito-operator/pull/905
- https://github.com/kiegroup/rhpam-kogito-operator/pull/44
<details>
<summary> …
=> BXMSPROD-1265: Conscious language initiative

.github/workflows/pull_request.yml, CONTRIBUTING.adoc, README.adoc, optaweb-vehicle-routing-backend/pom.xml, optaweb-vehicle-routing-docs/src/main/asciidoc/development-guide.adoc
https://github.com/kiegroup/optaplanner/pull/1466
https://github.com/kiegroup/optaweb-employee-rostering/pull/663
https://github.com/kiegroup/optaweb-vehicle-routing/pull/536
<!--
Thank you for submitting this pull request.
<details>
<summary>
</summary>
</details>
=> BXMSPROD-1265: master to main leftovers

optaweb-vehicle-routing-backend/src/main/java/org/optaweb/vehiclerouting/plugin/routing/RoutingConfig.java, optaweb-vehicle-routing-docs/src/main/asciidoc/run-noscript.adoc, runLocally.sh, runOnOpenShift.sh
<details>
<summary>
</summary>
</details>
=> Use HTTPS in Geofabrik URLs

.github/workflows/pull_request.yml
**Thank you for submitting this pull request**
**JIRA**: https://issues.redhat.com/browse/BXMSPROD-1475
**referenced Pull Requests**: 
* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1770
* https://github.com/kiegroup/kie-soup/pull/228
* https://github.com/kiegroup/droolsjbpm-knowledge/pull/549
* https://github.com/kiegroup/drools/pull/3835
* https://github.com/kiegroup/optaplanner/pull/1577
* https://github.com/kiegroup/lienzo-core/pull/152
* https://github.com/kiegroup/lienzo-tests/pull/126
* https://github.com/kiegroup/appformer/pull/1197
* https://github.com/kiegroup/kie-uberfire-extensions/pull/124
* https://github.com/kiegroup/jbpm/pull/2024
* https://github.com/kiegroup/kie-jpmml-integration/pull/65
* https://github.com/kiegroup/droolsjbpm-integration/pull/2607
* …
=> BXMSPROD-1475 maven version

.github/workflows/pull_request.yml
https://issues.redhat.com/browse/BXMSPROD-1543
- https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1819
<details>
<summary>
</summary>
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used on command line locally or in Github Actions workflow(s), in case …
=> BXMSPROD-1543 to point to kogito-pipelines composite actions

.github/workflows/pull_request.yml
* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1819
<details>
<summary>
</summary>
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used on command line locally or in Github Actions workflow(s), in case you need to change multiple repositories and …
=> [7.x] BXMSPROD-1543 to align composite-actions with the ones from kogito-pipelines

.github/workflows/pull_request.yml
https://github.com/kiegroup/optaweb-vehicle-routing/pull/602
=> [8.14.x] BXMSPROD-1542 definition-file eval expression

optaweb-vehicle-routing-docs/src/main/asciidoc/development-guide.adoc, optaweb-vehicle-routing-docs/src/main/asciidoc/run-openshift.adoc
https://docs.asciidoctor.org/asciidoc/latest/text/quotation-marks-and-apostrophes/
<details>
<summary>
</summary>
* for a <b>Quarkus LTS check</b> please add comment: <b>Jenkins run LTS</b>
* for a …
=> Use curved quotes

optaweb-vehicle-routing-frontend/package.json
<details>
<summary>
</summary> …
=> Keep dependencies sorted

pom.xml
- Upgrade frontend-maven-plugin `1.10.0` -> `1.11.3`, which correctly installs npm on Apple Silicon.
Same issue as:
https://github.com/kiegroup/optaweb-employee-rostering/issues/608
<details>
<summary>
</summary>
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be …
=> Upgrade frontend-maven-plugin for Apple Silicon support

.github/pull_request_template.md, .github/workflows/full-downstream.yml
[BXMSPROD-1601](https://issues.redhat.com/browse/BXMSPROD-1601)
**referenced Pull Requests**: _(please edit the URLs of referenced pullrequests if they exist)_
* https://github.com/kiegroup/kie-soup/pull/245
* https://github.com/kiegroup/droolsjbpm-knowledge/pull/584
* https://github.com/kiegroup/drools/pull/4083
* https://github.com/kiegroup/optaplanner/pull/1745
* https://github.com/kiegroup/lienzo-core/pull/160
* https://github.com/kiegroup/lienzo-tests/pull/133
* https://github.com/kiegroup/appformer/pull/1224
* https://github.com/kiegroup/kie-uberfire-extensions/pull/130
* https://github.com/kiegroup/jbpm/pull/2081
* https://github.com/kiegroup/droolsjbpm-integration/pull/2675
* https://github.com/kiegroup/kie-wb-playground/pull/126
* …
=> BXMSPROD-1601 provide FDB github action for RHBA project

optaweb-vehicle-routing-frontend/package-lock.json
Before:
79 vulnerabilities (56 moderate, 20 high, 3 critical)
`npm audit fix`
After:
71 vulnerabilities (55 moderate, 14 high, 2 critical)
<details>
<summary>
</summary>
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used on command line locally or in Github …
=> Reduce vulnerabilities in npm dependencies

.github/workflows/pull_request.yml
Signed-off-by: Lukáš Petrovický <lpetrovi@redhat.com>
<details>
<summary>
</summary> …
=> Enable JDK 18 on Pull Requests

.ci/jenkins/dsl/test.sh, .github/workflows/jenkins-tests-PR.yml, runLocally.sh
https://issues.redhat.com/browse/KOGITO-7101
Depends on https://github.com/kiegroup/kogito-pipelines/pull/435
=> KOGITO-7101 Correct DSL tests

optaweb-vehicle-routing-frontend/package-lock.json, optaweb-vehicle-routing-frontend/package.json
https://issues.redhat.com/browse/BXMSPROD-1700
<details>
<summary>
</summary> …
=> [BXMSPROD-1700] upgrade lock-treatment-tool to version ^0.1.0

optaweb-vehicle-routing-frontend/.eslintrc.json, optaweb-vehicle-routing-frontend/package-lock.json, optaweb-vehicle-routing-frontend/package.json, optaweb-vehicle-routing-frontend/src/react-app-env.d.ts, optaweb-vehicle-routing-frontend/src/ui/App.tsx
<details>
<summary>
</summary> …
=> Clean up after license headers removal

.github/workflows/full-downstream.yml, .github/workflows/pull_request.yml
Related PRs:
- https://github.com/kiegroup/kogito-pipelines/pull/543
- https://github.com/kiegroup/kogito-runtimes/pull/2317
- https://github.com/kiegroup/kogito-apps/pull/1407
- https://github.com/kiegroup/kogito-examples/pull/1324
- https://github.com/kiegroup/drools/pull/4525
- https://github.com/kiegroup/optaplanner/pull/2063
- https://github.com/kiegroup/optaweb-vehicle-routing/pull/728
- https://github.com/kiegroup/optaweb-employee-rostering/pull/841
=> [KOGITO-7504] Update Maven to 3.8.6

optaweb-vehicle-routing-frontend/package-lock.json
See https://github.com/browserslist/browserslist#browsers-data-updating.
<details>
<summary>
</summary>
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used on command line locally or in Github Actions workflow(s), in case you need to change multiple repositories …
=> Update Browserslist DB

optaweb-vehicle-routing-frontend/cypress/fixtures/response-garz.json, optaweb-vehicle-routing-frontend/cypress/fixtures/response-hoppenrade.json, optaweb-vehicle-routing-frontend/cypress/integration/fromLocationsToRoute.js, optaweb-vehicle-routing-frontend/package-lock.json
Backporting #583 to 8.13.x.
https://issues.redhat.com/browse/RHPAM-4436
<details>
<summary>
</summary>
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used on command line locally or in Github Actions workflow(s), in case you need to change multiple repositories …
=> [8.13.x] RHPAM-4436: Mock Nominatim API in the Cypress test

optaweb-vehicle-routing-frontend/package-lock.json
**Thank you for submitting this pull request**
**JIRA**:
- https://issues.redhat.com/browse/RHPAM-4271
**referenced Pull Requests**: 
- https://github.com/kiegroup/appformer/pull/1304
- https://github.com/kiegroup/kie-wb-common/pull/3778
- https://github.com/kiegroup/optaweb-vehicle-routing/pull/753
- https://github.com/kiegroup/optaweb-employee-rostering/pull/854
- https://github.com/kiegroup/kogito-apps/pull/1461
Upgrade `minimist` package to version `1.2.6`.
**NB**: No need to fix this in `main` branch since it is already fixed.
<details>
<summary>
</summary>
Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method …
=> [7.67.x] [RHPAM-4271] CVE-2021-44906: Upgrade minimist to 1.2.6

optaweb-vehicle-routing-backend/src/main/java/org/optaweb/vehiclerouting/plugin/planner/VehicleRoutingConstraintProvider.java
<details>
<summary>
</summary> …
=> PLANNER-1709 Avoid deprecated penalize() overloads

.ci/jenkins/Jenkinsfile.init-branch
https://issues.redhat.com/browse/KOGITO-8043
Related:
- https://github.com/kiegroup/kogito-pipelines/pull/635
- https://github.com/kiegroup/optaplanner/pull/2220
- https://github.com/kiegroup/optaweb-vehicle-routing/pull/761
- https://github.com/kiegroup/optaplanner-quickstarts/pull/416
=> [8.28.x] KOGITO-8043 Jenkins node master -> built-in

.ci/jenkins/dsl/Jenkinsfile.seed
https://issues.redhat.com/browse/KOGITO-8043
Related:
- https://github.com/kiegroup/kogito-pipelines/pull/637
- https://github.com/kiegroup/kogito-runtimes/pull/2528
- https://github.com/kiegroup/kogito-examples/pull/1426
- https://github.com/kiegroup/kogito-images/pull/1345
- https://github.com/kiegroup/kogito-operator/pull/1296
- https://github.com/kiegroup/optaplanner/pull/2222
- https://github.com/kiegroup/optaweb-vehicle-routing/pull/762
- https://github.com/kiegroup/optaplanner-quickstarts/pull/417
=> [8.13.x] KOGITO-8043 Jenkins node master -> built-in

.ci/jenkins/Jenkinsfile.init-branch
https://issues.redhat.com/browse/KOGITO-8043
Related:
- https://github.com/kiegroup/kogito-pipelines/pull/631
- https://github.com/kiegroup/drools/pull/4723
- https://github.com/kiegroup/kogito-runtimes/pull/2525
- https://github.com/kiegroup/kogito-apps/pull/1483
- https://github.com/kiegroup/kogito-examples/pull/1423
- https://github.com/kiegroup/kogito-images/pull/1342
- https://github.com/kiegroup/kogito-operator/pull/1293
- https://github.com/kiegroup/kogito-docs/pull/218
- https://github.com/kiegroup/kie-tools/pull/1249
- https://github.com/kiegroup/optaplanner/pull/2219
- https://github.com/kiegroup/optaweb-vehicle-routing/pull/760
- https://github.com/kiegroup/optaplanner-quickstarts/pull/415
=> KOGITO-8043 Jenkins node master -> built-in

optaweb-vehicle-routing-frontend/package-lock.json, optaweb-vehicle-routing-frontend/package.json
https://issues.redhat.com/browse/RHPAM-4530
* https://github.com/kiegroup/optaweb-vehicle-routing/pull/766
* https://github.com/kiegroup/optaweb-vehicle-routing/pull/767
* https://github.com/kiegroup/optaweb-vehicle-routing/pull/768
<details>
<summary>
</summary>
[build-chain …
=> [7.x] RHPAM-4530 lock-treatment-tool upgraded to 0.2.1 CVE-2021-23383

optaweb-vehicle-routing-frontend/package-lock.json, optaweb-vehicle-routing-frontend/package.json
https://issues.redhat.com/browse/RHPAM-4530
* https://github.com/kiegroup/optaweb-vehicle-routing/pull/766
* https://github.com/kiegroup/optaweb-vehicle-routing/pull/767
* https://github.com/kiegroup/optaweb-vehicle-routing/pull/768
<details>
<summary>
</summary>
[build-chain …
=> [7.67.x] RHPAM-4530 lock-treatment-tool upgraded to 0.2.1 CVE-2021-23383

.ci/jenkins/dsl/test.sh, .github/workflows/jenkins-tests-PR.yml, .github/workflows/sonarcloud.yml
https://issues.redhat.com/browse/KOGITO-8110
- https://github.com/kiegroup/kogito-pipelines/pull/646
- https://github.com/kiegroup/drools/pull/4738
- https://github.com/kiegroup/kogito-runtimes/pull/2547
- https://github.com/kiegroup/kogito-apps/pull/1489
- https://github.com/kiegroup/kogito-examples/pull/1440
- https://github.com/kiegroup/kogito-images/pull/1348
- https://github.com/kiegroup/kogito-operator/pull/1305
- https://github.com/kiegroup/kogito-docs/pull/228
- https://github.com/kiegroup/optaplanner/pull/2242
- https://github.com/kiegroup/optaweb-vehicle-routing/pull/770
- https://github.com/kiegroup/optaplanner-quickstarts/pull/428
- https://github.com/kiegroup/kie-tools/pull/1271
=> KOGITO-8110 Correct GHA DSL checks

.github/workflows/full-downstream.yml, .github/workflows/pull_request.yml
- https://github.com/kiegroup/kogito-pipelines/pull/668
- https://github.com/kiegroup/drools/pull/4772
- https://github.com/kiegroup/optaplanner/pull/2268
- https://github.com/kiegroup/optaweb-vehicle-routing/pull/789
- https://github.com/kiegroup/optaplanner-quickstarts/pull/439
=> [8.29.x] Updated GHA for productized profile only

.github/workflows/jenkins-tests-PR.yml
Related PRs:
- https://github.com/kiegroup/optaplanner/pull/2277
- https://github.com/kiegroup/optaweb-vehicle-routing/pull/787
- https://github.com/kiegroup/optaplanner-quickstarts/pull/442
=> Correct GHA DSL check on release branch

.ci/jenkins/Jenkinsfile.setup-branch
- https://github.com/kiegroup/drools/pull/4977
- https://github.com/kiegroup/kogito-runtimes/pull/2794
- https://github.com/kiegroup/kogito-apps/pull/1623
- https://github.com/kiegroup/kogito-examples/pull/1565
- https://github.com/kiegroup/optaplanner/pull/2569
- https://github.com/kiegroup/optaweb-vehicle-routing/pull/844
- https://github.com/kiegroup/optaplanner-quickstarts/pull/509
=> Setup Branch: Update branch before deploy

.github/workflows/sonarcloud.yml
https://issues.redhat.com/browse/BXMSPROD-1973
- https://github.com/kiegroup/kogito-pipelines/pull/868
- https://github.com/kiegroup/drools-website/pull/241
- https://github.com/kiegroup/kogito-runtimes/pull/2811
- https://github.com/kiegroup/optaweb-vehicle-routing/pull/847
- https://github.com/kiegroup/optaplanner-website/pull/570
=> BXMSPROD-1973 Update GHA setup-java to v3

optaweb-vehicle-routing-backend/src/main/java/org/optaweb/vehiclerouting/plugin/routing/RoutingProperties.java, optaweb-vehicle-routing-backend/src/main/java/org/optaweb/vehiclerouting/service/demo/DemoProperties.java, optaweb-vehicle-routing-backend/src/main/java/org/optaweb/vehiclerouting/service/region/RegionProperties.java
Since the upgrade to Quarkus `2.16.4`, two tests have been failing and the backend does not start due to the following issue:
https://github.com/quarkusio/quarkus/issues/31554
I'm not adding a TODO note there as the discussion on the issue suggests this is the new status quo. I am watching the issue though; if they decide to fix it, I will make the interfaces non-public again.
<details>
<summary>
</summary>
Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to handle cross …
=> Make config interfaces public

optaweb-vehicle-routing-backend/pom.xml, optaweb-vehicle-routing-backend/src/test/java/org/optaweb/vehiclerouting/domain/CoordinatesTest.java, optaweb-vehicle-routing-backend/src/test/java/org/optaweb/vehiclerouting/domain/LocationTest.java, optaweb-vehicle-routing-backend/src/test/java/org/optaweb/vehiclerouting/service/demo/DemoServiceTest.java, optaweb-vehicle-routing-backend/src/test/java/org/optaweb/vehiclerouting/service/region/RegionServiceTest.java
<details>
<summary>
</summary> …
=> Upgrade Pitest to 1.11.4 and improve test coverage
