kiegroup/optaweb-vehicle-routing

- optaweb-vehicle-routing-backend/pom.xml
- optaweb-vehicle-routing-backend/src/main/java/org/optaweb/vehiclerouting/plugin/persistence/DistanceEntity.java
- optaweb-vehicle-routing-backend/src/main/java/org/optaweb/vehiclerouting/plugin/persistence/DistanceKey.java
- optaweb-vehicle-routing-backend/src/test/java/org/optaweb/vehiclerouting/domain/LatLngTest.java
- optaweb-vehicle-routing-backend/src/test/java/org/optaweb/vehiclerouting/domain/LocationTest.java
- optaweb-vehicle-routing-backend/src/test/java/org/optaweb/vehiclerouting/plugin/persistence/DistanceEntityTest.java
- optaweb-vehicle-routing-backend/src/test/java/org/optaweb/vehiclerouting/plugin/persistence/DistanceRepositoryImplTest.java
- optaweb-vehicle-routing-backend/src/test/java/org/optaweb/vehiclerouting/plugin/persistence/LocationEntityTest.java
- optaweb-vehicle-routing-backend/src/test/java/org/optaweb/vehiclerouting/plugin/persistence/LocationRepositoryImplTest.java
- optaweb-vehicle-routing-backend/src/test/java/org/optaweb/vehiclerouting/plugin/persistence/integration_tests/DistanceRepositoryIntegrationTest.java
- optaweb-vehicle-routing-backend/src/test/java/org/optaweb/vehiclerouting/plugin/persistence/integration_tests/LocationRepositoryIntegrationTest.java
Line Coverage: 74% (386/525)
Mutation Coverage: 72% (452/627)
Execution time (Pitest total): 43 s
This is an improvement despite excluding `@DataJpaTest`s. Explanation:
- The slow (integration) DataJpaTests were replaced by unit tests that mock Spring CrudRepository.
- A few new tests were added.
- Number of mutations was slightly reduced by avoiding calls to `org.slf4j`.
> Pitest improvements

- .travis.yml
- Keep the cache clean (don't pollute it with build artifacts). This is done by avoiding `mvn install`.
- Cache Maven Wrapper. Unless a dependency upgrade occurs, we now have 0 Maven downloads during the build.
- Disable Git shallow clone. This might unlock some SCM related features on SonarCloud. At least it removes a warning visible in the UI.
> Improve backend build on Travis

- optaweb-vehicle-routing-frontend/src/ui/components/UnderConstruction.test.tsx
- optaweb-vehicle-routing-frontend/src/ui/components/UnderConstruction.tsx
- optaweb-vehicle-routing-frontend/src/ui/components/__snapshots__/UnderConstruction.test.tsx.snap
- optaweb-vehicle-routing-frontend/src/ui/pages/Vehicles.test.tsx
- optaweb-vehicle-routing-frontend/src/ui/pages/__snapshots__/Vehicles.test.tsx.snap
Work in progress could have been interpreted as if there was a background task going on (e.g. loading data from server).
> Rename WorkInProgress to UnderConstruction

- .travis.yml
- README.adoc
- optaweb-vehicle-routing-backend/pom.xml
- optaweb-vehicle-routing-backend/src/main/java/org/optaweb/vehiclerouting/domain/Coordinates.java
- optaweb-vehicle-routing-backend/src/main/java/org/optaweb/vehiclerouting/plugin/websocket/PortableLocation.java
- optaweb-vehicle-routing-backend/src/test/java/org/optaweb/vehiclerouting/plugin/websocket/PortableLocationTest.java
- optaweb-vehicle-routing-backend/src/test/resources/org/optaweb/vehiclerouting/plugin/websocket/portable-location.json
- optaweb-vehicle-routing-frontend/README.adoc
- optaweb-vehicle-routing-frontend/package-lock.json
- optaweb-vehicle-routing-frontend/package.json
- optaweb-vehicle-routing-frontend/pom.xml
- pom.xml
- Root POM is now parent of backend and frontend modules. `kie-parent` is now parent of root POM.
- `spring-boot-starter-parent` is no longer parent of backend but we import `spring-boot-dependencies` for dependency management.
- Overriding a few versions from `kie-parent` in order to build successfully under its dependency management.
- Bound npm scripts to Maven phases that make most sense so if you, for example, run `mvn generate-resources` Maven doesn't run tests and the production build.
- Removed Jacoco and Sonar plugin configurations that are already defined in `kie-parent`. Keeping pull request and branch analysis profiles that activate smartly on Travis.
- Changed SonarCloud project's key, renamed root pom to `org.optaweb.vehiclerouting:optaweb-vehicle-routing`.
> Prepare the repository to be added to KIE group's repository-list.txt

- pom.xml
Necessary to comply with Enforcer's `banDuplicateClasses` rule.
This is a temporary solution. Once we drop dependency on `optaplanner-examples`, which we only have to get VRP domain for free, the colliding artifacts will disappear.
> Exclude a few javax APIs that are already dragged in by Spring Boot

- pom.xml
1.4.199 is what we had before inheriting kie-parent, which uses an outdated
version 1.3.173.
Another reason why I want prevent users from experiencing the upgrade
from 1.3.x to 1.4.x is that the DB file name has changed
(vrp.h2.db -> vrp.mv.db). We would need to document this in release
notes.
> Upgrade to latest H2

- optaweb-vehicle-routing-distribution/src/main/assembly/assembly-optaweb-vehicle-routing.xml
@yurloc I finally had to add distribution folder to the sources folder, otherwise the source code from distribution assembly file won't compile.
> BXMSPROD-495 distribution not excluded from assembly

- .travis.yml
Add Travis script that will fail the build if distribution isn't assembled correctly (it only runs `mvn validate` in it).
> Add sanity check script for the distribution assembly

- .travis.yml
This Travis build phase will make sure the build fails whenever the Red Hat registry is accidentally committed to package-lock.json.
> Fail Travis build if package-lock references redhat.com registry

- optaweb-vehicle-routing-frontend/pom.xml
From nodejs.org [download](https://nodejs.org/en/download/) site:
Latest LTS Version: 10.16.3 (includes npm 6.9.0)
> Update Node.js to latest LTS

- optaweb-vehicle-routing-frontend/pom.xml
The Frontend Maven plugin's configuration properties can already be
overridden using System properties without any extra POM modifications.
Tested locally. Cleaned up the downloaded and unpacked binaries first:
- `rm -r node/`
- `rm -r ~/.m2/repository/com/github/eirslett/{node,npm}`
This forces Frontend plugin to re-download binaries:
```
[INFO] --- frontend-maven-plugin:1.7.5:install-node-and-npm (install node and npm) @ optaweb-vehicle-routing-frontend ---
[INFO] Installing node version v11.6.0
[INFO] Downloading http://rcm-guest.app.eng.bos.redhat.com/rcm-guest/staging/rhba/dist/node/v11.6.0/node-v11.6.0-linux-x64.tar.gz to /home/jlocker/.m2/repository/com/github/eirslett/node/11.6.0/node-11.6.0-linux-x64.tar.gz
[INFO] No proxies configured
[INFO] No proxy was configured, downloading …
```
> Remove unnecessary properties

- optaweb-vehicle-routing-frontend/pom.xml
Jenkins uses `-Dmaven.test.failure.ignore` to run the complete build
even if some tests are failing. Frontend plugin honors this property
in such a way that any goal ran in the test phase doesn't fail
the build (even if it returns non-zero code) but we want typecheck
and lint to fail the build.
Frontend plugin issue with related information: https://github.com/eirslett/frontend-maven-plugin/issues/534.
> Run lint in compile phase to fail Maven build on Jenkins

- optaweb-vehicle-routing-distribution/src/main/assembly/assembly-optaweb-vehicle-routing.xml
Gitignores are imporant part of the source code. They provide
information about which files are not intended to be committed to the
SCM. This could be useful if user initializes a Git repository in the
source distribution.
> Don't use default excludes in distribution assembly to keep .gitignores

- optaweb-vehicle-routing-frontend/cypress.json
- optaweb-vehicle-routing-frontend/package.json
Jenkins jobs expect test results to be stored in
**/target/*-reports/TEST-*.xml
> Place all frontend test reports in a single subdirectory

- optaweb-vehicle-routing-frontend/docker/Dockerfile
- provision.sh
OpenShift Online complains about a build with docker strategy for the
frontend. However backend build with the same strategy is OK. The only
difference is that frontend build defines an environment variable with
backend URL. The attempt to create the build failed with:
error: failed to set env: admission webhook "validate.build.create" denied
the request: Builds with docker strategy are prohibited on this cluster
Removing the enviroment variable makes the build work (even thought it
still uses the docker strategy ¯\\_(ツ)_/¯). Might be an OpenShift bug.
The same error as above is produced by:
oc set env bc/frontend BACKEND_URL=http://backend:8080
so maybe it's just that docker builds can't have environment variables.
> Make http://backend:8080 default BACKEND_URL in frontend Dockerfile

- .travis.yml
- Fail Maven build if downloading dependencies failed.
- Do not download sources (should be the default but seems to be
broken).
> Fix go-offline

- README.adoc
Modify instruction to use dev profile when running the Spring Boot backend. Prevents user from getting `Caused by: org.hibernate.HibernateException: Access to DialectResolutionInfo cannot be null when 'hibernate.dialect' not set` exception when running the backend.
> Fix backend run instruction

- optaweb-vehicle-routing-frontend/pom.xml
https://issues.jboss.org/browse/RHDM-1129
depends on
- https://issues.jboss.org/browse/BXMSPROD-597 https://github.com/kiegroup/optaweb-vehicle-routing/pull/234
- and https://issues.jboss.org/browse/BXMSPROD-580 https://github.com/kiegroup/optaweb-vehicle-routing/pull/228
> RHDM-1129: locktt execution added to productized profile, prepare-package phase

- optaweb-vehicle-routing-backend/pom.xml
- optaweb-vehicle-routing-docs/pom.xml
- optaweb-vehicle-routing-standalone/pom.xml
https://maven.apache.org/pom.html#Plugin_Management
It makes no sense to use `<pluginManagement/>` in a leaf POM. By removing unnecessary plugin management we achieve less code and better coherence.
> Avoid unnecessary plugin management

- optaweb-vehicle-routing-backend/Dockerfile
Fixes the problem with downloading OSM file from an HTTPS URL. Tested locally with CRC.
> PLANNER-1813: Use UBI-based image for backend

- .travis.yml
- optaweb-vehicle-routing-backend/pom.xml
- optaweb-vehicle-routing-docs/pom.xml
This fixes a problem when building on OpenJDK 11.
See also
- https://github.com/asciidoctor/asciidoctorj/issues/515.
- https://stackoverflow.com/questions/43574426/how-to-resolve-java-lang-noclassdeffounderror-javax-xml-bind-jaxbexception-in-j
After 7.33.0 release, I'll upgrade the plugin in kie-parent and remove overrides in all repositories: https://issues.redhat.com/browse/PLANNER-1839.
> PLANNER-1782: Upgrade AsciidoctorJ and Asciidoctor Maven Plugin

- optaweb-vehicle-routing-backend/Dockerfile
- runOnOpenShift.sh
The `--spring.profiles.active` argument would prevent profile activation
using environment variables.
Aligns VR with ER (https://github.com/kiegroup/optaweb-employee-rostering/pull/379).
> Do not hardcode production profile in the backend Dockerfile

- pom.xml
javax.validation is no longer in the dependency tree.
> Remove obsolete javax.validation version override

- pom.xml
This artifacts is already managed by kie-parent where it receives Dependabot updates. No longer needs overriding.
> Remove jackson-databind override

- optaweb-vehicle-routing-frontend/pom.xml
They are now managed by kie-parent.
PR group:
- https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1273
- https://github.com/kiegroup/appformer/pull/943
- https://github.com/kiegroup/droolsjbpm-integration/pull/2064
- https://github.com/kiegroup/kie-wb-common/pull/3269
- https://github.com/kiegroup/optaweb-vehicle-routing/pull/296
- https://github.com/kiegroup/optaweb-employee-rostering/pull/425
> BXMSPROD-741: Remove Node and npm versions

- optaweb-vehicle-routing-backend/pom.xml
- optaweb-vehicle-routing-backend/src/main/java/org/optaweb/vehiclerouting/plugin/websocket/DataSetDownloadController.java
- optaweb-vehicle-routing-backend/src/test/java/org/optaweb/vehiclerouting/plugin/websocket/DataSetDownloadControllerTest.java
- pom.xml
Spring Framework and Spring Boot were upgraded to 5.2.5 and 2.2.6 in https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1297.
Removing deprecated API usage in response to the upgrade.
Also moving Surefire configuration with `@{jacoco.agent.argLine}` to a profile to make it possible to run tests from IDEA. @rsynek I recently noticed this works in `optaplanner` repo. Not sure if there has been any fix on IntelliJ side.
> Remove deprecated API usage after Spring upgrade

- optaweb-vehicle-routing-backend/src/main/resources/application.properties
- runLocally.sh
The DB file name still defaults to `vrp` but it can be configured using `app.persistence.h2-filename` property. The run script sets the property to the region name so that each region has a dedicated db file. That is convenient when switching between different regions.
Example:
You can start with Belgium, load cities data set, shut down without cleaning the database and switch to France. The app will now start successfully because it will no longer try to load Belgian cities created in the previous run.
> PLANNER-1995: Use a database file per region when using run script

- .travis.yml
Java 8 has been deprecated by Sonar.
> Run Sonar analysis on Java 11

- optaweb-vehicle-routing-frontend/cypress/integration/fromLocationsToRoute.js
- optaweb-vehicle-routing-frontend/package.json
- optaweb-vehicle-routing-frontend/src/ui/App.tsx
- optaweb-vehicle-routing-frontend/src/ui/__snapshots__/App.test.tsx.snap
- optaweb-vehicle-routing-frontend/src/ui/header/Navigation.test.tsx
- optaweb-vehicle-routing-frontend/src/ui/header/Navigation.tsx
- optaweb-vehicle-routing-frontend/src/ui/header/__snapshots__/Navigation.test.tsx.snap
- optaweb-vehicle-routing-frontend/src/ui/pages/Demo.tsx
- optaweb-vehicle-routing-frontend/src/ui/pages/InfoBlock.test.tsx
- optaweb-vehicle-routing-frontend/src/ui/pages/InfoBlock.tsx
- optaweb-vehicle-routing-frontend/src/ui/pages/Route.tsx
- optaweb-vehicle-routing-frontend/src/ui/pages/__snapshots__/Demo.test.tsx.snap
- optaweb-vehicle-routing-frontend/src/ui/pages/__snapshots__/InfoBlock.test.tsx.snap
- optaweb-vehicle-routing-frontend/src/ui/pages/__snapshots__/Route.test.tsx.snap
- optaweb-vehicle-routing-frontend/src/ui/pages/common.ts
Additional improvements:
- Made location list width fixed.
- Added icons to info blocks (vehicles, visits, distance).
- Added `npm run update-snapshots` script that just runs tests and updates snapshots in non-interactive mode.
> PLANNER-1897: Make Demo the landing page

- runOnOpenShift.sh
Made runOnOpenShift.sh to store configurations
into Deployments instead of DeploymentsConfig
Cherry-pick of #334 
@yurloc
> Change configuration to new OCP 4.5.1 standard

- optaweb-vehicle-routing-backend/src/main/java/org/optaweb/vehiclerouting/domain/CountryCodeValidator.java
- optaweb-vehicle-routing-backend/src/main/java/org/optaweb/vehiclerouting/domain/Route.java
- optaweb-vehicle-routing-backend/src/main/java/org/optaweb/vehiclerouting/domain/RoutingPlan.java
- optaweb-vehicle-routing-backend/src/main/java/org/optaweb/vehiclerouting/plugin/persistence/LocationRepositoryImpl.java
- optaweb-vehicle-routing-backend/src/main/java/org/optaweb/vehiclerouting/plugin/persistence/VehicleRepositoryImpl.java
- optaweb-vehicle-routing-backend/src/main/java/org/optaweb/vehiclerouting/plugin/planner/RouteChangedEventPublisher.java
- optaweb-vehicle-routing-backend/src/main/java/org/optaweb/vehiclerouting/plugin/routing/GraphHopperRouter.java
- optaweb-vehicle-routing-backend/src/main/java/org/optaweb/vehiclerouting/plugin/websocket/PortableRoutingPlanFactory.java
- optaweb-vehicle-routing-backend/src/main/java/org/optaweb/vehiclerouting/plugin/websocket/WebSocketController.java
- optaweb-vehicle-routing-backend/src/main/java/org/optaweb/vehiclerouting/service/demo/RoutingProblemConfig.java
- optaweb-vehicle-routing-backend/src/main/java/org/optaweb/vehiclerouting/service/demo/RoutingProblemList.java
- optaweb-vehicle-routing-backend/src/main/java/org/optaweb/vehiclerouting/service/demo/dataset/DataSetMarshaller.java
- optaweb-vehicle-routing-backend/src/main/java/org/optaweb/vehiclerouting/service/route/RouteListener.java
- optaweb-vehicle-routing-backend/src/main/java/org/optaweb/vehiclerouting/service/route/ShallowRoute.java
- optaweb-vehicle-routing-backend/src/test/java/org/optaweb/vehiclerouting/plugin/planner/weight/DepotAngleVisitDifficultyWeightFactoryTest.java
This improves readability because it's shorter and in the context of a stream it's always clear where `toList()` comes from.
> Use static imports for Collectors methods

- optaweb-vehicle-routing-backend/src/main/java/org/optaweb/vehiclerouting/service/demo/dataset/DataSet.java
- optaweb-vehicle-routing-backend/src/main/java/org/optaweb/vehiclerouting/service/demo/dataset/DataSetMarshaller.java
When a YAML data set contains:
```
vehicles:
```
meaning the attribute is present without a value, the corresponding Java
field is set to null regardless the initial value of the field. We can't
control this. The solution is to make the code working with DataSet
null-safe.
> Make DataSetMarshaller null-safe

- .travis.yml
The following error blocks #384: 
```
$ mvn de.qaware.maven:go-offline-maven-plugin:1.2.3:resolve-dependencies -DfailOnErrors -DdownloadSources=false -Prun-code-coverage,sonarcloud-analysis --quiet
[ERROR] Error downloading dependencies for project
[ERROR] Could not find artifact org.optaweb.vehiclerouting:optaweb-vehicle-routing-docs:zip:8.0.0-SNAPSHOT in sonatype-snapshots (https://oss.sonatype.org/content/repositories/snapshots/)
```
The plugin tries to download the docs module that hasn't been released yet. It's a bug in the plugin (qaware/go-offline-maven-plugin/issues/16) which has been fixed in 1.2.4.
<details>
<summary>
</summary>
* for a <b>full …
> Upgrade go-offline-maven-plugin to 1.2.7

- optaweb-vehicle-routing-backend/pom.xml
- optaweb-vehicle-routing-backend/src/main/java/org/optaweb/vehiclerouting/plugin/planner/change/AddVehicle.java
- optaweb-vehicle-routing-backend/src/main/java/org/optaweb/vehiclerouting/plugin/planner/change/AddVisit.java
- optaweb-vehicle-routing-backend/src/main/java/org/optaweb/vehiclerouting/plugin/planner/change/ChangeVehicleCapacity.java
- optaweb-vehicle-routing-backend/src/main/java/org/optaweb/vehiclerouting/plugin/planner/change/RemoveVehicle.java
- optaweb-vehicle-routing-backend/src/main/java/org/optaweb/vehiclerouting/plugin/planner/change/RemoveVisit.java
- optaweb-vehicle-routing-backend/src/main/java/org/optaweb/vehiclerouting/plugin/planner/change/package-info.java
- optaweb-vehicle-routing-backend/src/test/java/org/optaweb/vehiclerouting/plugin/planner/change/AddVehicleTest.java
- optaweb-vehicle-routing-backend/src/test/java/org/optaweb/vehiclerouting/plugin/planner/change/AddVisitTest.java
- optaweb-vehicle-routing-backend/src/test/java/org/optaweb/vehiclerouting/plugin/planner/change/ChangeVehicleCapacityTest.java
- optaweb-vehicle-routing-backend/src/test/java/org/optaweb/vehiclerouting/plugin/planner/change/RemoveVehicleTest.java
- optaweb-vehicle-routing-backend/src/test/java/org/optaweb/vehiclerouting/plugin/planner/change/RemoveVisitTest.java
- optaweb-vehicle-routing-distribution/pom.xml
- optaweb-vehicle-routing-docs/pom.xml
- optaweb-vehicle-routing-frontend/pom.xml
- optaweb-vehicle-routing-standalone/pom.xml
- pom.xml
Depends on / supersedes  https://github.com/kiegroup/optaweb-vehicle-routing/pull/379
https://issues.redhat.com/browse/PLANNER-2201
https://issues.redhat.com/browse/PLANNER-2199
<details>
<summary>
</summary>
</details>
> PLANNER-2199 & PLANNER-2201: Upgrade to 8.0.0-SNAPSHOT and replace kie-parent with optaplanner-build-parent

- .travis.yml
When #384 is merged it will no longer be possible to build the project on Java 8.
=> Therefore,
- Replacing Java 8 with Java 11,
- and replacing Java 11 with the latest - Java 15.
None.
None.
<details>
<summary>
</summary>
</details>
> Drop OpenJDK 8, add OpenJDK 15

- optaweb-vehicle-routing-frontend/package-lock.json
<details>
<summary>
</summary>
</details>
> Upgrade vulnerable node-forge to 0.10.0

- .travis.yml
- optaweb-vehicle-routing-backend/pom.xml
- pom.xml
Remove all JaCoCo configuration to avoid interference with
optaplanner-build-parent. As a bonus, we get multi-module coverage
report and a slight coverage percentage increase (Spring *Properties and
*Config classes get better coverage for some reason).
<details>
<summary>
</summary>
</details>
> Fix SonarCloud coverage report

- optaweb-vehicle-routing-backend/Dockerfile
- optaweb-vehicle-routing-backend/pom.xml
- optaweb-vehicle-routing-distribution/src/main/assembly/assembly-optaweb-vehicle-routing.xml
- optaweb-vehicle-routing-docs/src/main/asciidoc/development-guide.adoc
- optaweb-vehicle-routing-docs/src/main/asciidoc/quickstart.adoc
- optaweb-vehicle-routing-docs/src/main/asciidoc/run-locally.adoc
- optaweb-vehicle-routing-docs/src/main/asciidoc/run-noscript.adoc
- pom.xml
Cleans up POMs, documentation and Dockerfiles after bumping to OptaPlanner 8.0 and replacing `kie-parent` with `optaplanner-build-parent` in #384.
<details>
<summary>
</summary>
</details>
> Clean up 8.x

- optaweb-vehicle-routing-frontend/src/ui/components/RouteMap.tsx
- optaweb-vehicle-routing-frontend/src/ui/components/__snapshots__/RouteMap.test.tsx.snap
- Thicker lines make it easier to discern a route from a road when the colors are similar.
- Transparency helps to see where multiple routes overlap.
- [Smoothness factor](https://leafletjs.com/reference-1.7.1.html#polyline-smoothfactor) sacrifices accuracy for performance and smoother look.
None.
<details>
<summary>
</summary>
* for an <b>upstream build</b> please add comment: <b>Jenkins run …
> Nicer polylines

- pom.xml
Currently it's wrongly detected as 8 during Sonar Scanner execution:
[INFO] Configured Java source version (sonar.java.source): 8
According to documentation [1], sonar.java.source affects rule
activation. Using a lower version (8) might cause some Java 11 rules no
being activated.
[1] https://docs.sonarqube.org/latest/analysis/languages/java/
<details>
<summary>
</summary>
* for an <b>upstream …
> Remove maven.compiler.release which is inherited from optaplanner-build-parent

- optaweb-vehicle-routing-backend/src/test/java/org/optaweb/vehiclerouting/plugin/persistence/DistanceRepositoryIntegrationTest.java
- optaweb-vehicle-routing-backend/src/test/java/org/optaweb/vehiclerouting/plugin/persistence/LocationRepositoryIntegrationTest.java
It's already declared by `@DataJpaTest`.
Discovered when reviewing kiegroup/optaweb-employee-rostering#528.
<details>
<summary>
</summary>
</details>
> Remove redundant SpringExtension

- .github/workflows/pull_request.yml
https://issues.redhat.com/browse/BXMSPROD-1062
related PRs:
* https://github.com/kiegroup/kie-soup/pull/164
* https://github.com/kiegroup/droolsjbpm-knowledge/pull/483
* https://github.com/kiegroup/drools/pull/3216
* https://github.com/kiegroup/optaplanner/pull/1013
* https://github.com/kiegroup/jbpm/pull/1795
* https://github.com/kiegroup/kie-jpmml-integration/pull/47
* https://github.com/kiegroup/droolsjbpm-integration/pull/2309
* https://github.com/kiegroup/openshift-drools-hacep/pull/104
* https://github.com/kiegroup/droolsjbpm-tools/pull/123
* https://github.com/kiegroup/lienzo-core/pull/139
* https://github.com/kiegroup/lienzo-tests/pull/112
* https://github.com/kiegroup/appformer/pull/1074
* https://github.com/kiegroup/kie-uberfire-extensions/pull/110
* …
> [master] BXMSPROD-1062 kiegroup/github-action-build-chain updated

- optaweb-vehicle-routing-backend/pom.xml
- optaweb-vehicle-routing-backend/src/main/resources/application.properties
It was used to be brought by one of the Spring Boot Starters but it
disappeared during upgrade to Spring Boot 2.3.4.
<details>
<summary>
</summary>
</details>
> Prepare for Spring Boot upgrade (add validation dependencies, set JPA bootstrap mode)

- .travis.yml
- Jenkinsfile
- optaweb-vehicle-routing-frontend/.gitignore
- pom.xml
- Jenkins has a more secure way of sharing the SonarCloud token.
- Travis changes pricing model. I'm currently unable to run builds on
Travis CI.
Related reading:
- https://blog.travis-ci.com/2020-11-02-travis-ci-new-billing
- https://travis-ci.community/t/org-com-migration-unexpectedly-comes-with-a-plan-change-for-oss-what-exactly-is-the-new-deal/10567
- https://www.jeffgeerling.com/blog/2020/travis-cis-new-pricing-plan-threw-wrench-my-open-source-works
https://issues.redhat.com/browse/PLANNER-2318
<details>
<summary>
</summary>
* for a <b>compile downstream build</b> please add …
> PLANNER-2318: Move SonarCloud analysis from Travis to Jenkins

- optaweb-vehicle-routing-backend/pom.xml
- optaweb-vehicle-routing-standalone/pom.xml
Fixes the build broken by https://github.com/kiegroup/optaplanner/pull/1141
`Error assembling JAR: Invalid automatic module name: ''`
<details>
<summary>
</summary>
</details>
> Define automatic module name

- .github/workflows/pull_request.yml
JIRA
https://issues.redhat.com/browse/BXMSPROD-1214
https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1595
https://github.com/kiegroup/kie-soup/pull/182
https://github.com/kiegroup/droolsjbpm-knowledge/pull/504
https://github.com/kiegroup/drools/pull/3406
https://github.com/kiegroup/optaplanner/pull/1177
https://github.com/kiegroup/lienzo-core/pull/141
https://github.com/kiegroup/lienzo-tests/pull/113
https://github.com/kiegroup/appformer/pull/1110
https://github.com/kiegroup/kie-uberfire-extensions/pull/111
https://github.com/kiegroup/jbpm/pull/1875
https://github.com/kiegroup/kie-jpmml-integration/pull/49
https://github.com/kiegroup/droolsjbpm-integration/pull/2405
https://github.com/kiegroup/kie-wb-playground/pull/103
https://github.com/kiegroup/kie-wb-common/pull/3579 …
> BXMSPROD-1214 Install takari error workaround (master)

- .github/workflows/pull_request.yml
- .mvn/extensions.xml
https://issues.redhat.com/browse/BXMSPROD-1228
- https://github.com/kiegroup/optaweb-employee-rostering/pull/584
<details>
<summary>
</summary>
</details>
> [8.3.x] BXMSPROD-1228: Add Takari extension to fix GitHub Actions

- .github/workflows/pull_request.yml
The config URL with the `${BRANCH}` variable works on master but will break
every time an 8.x release branch is created because there is no matching
8.x branch in droolsjbpm-build-bootstrap.
All OptaWeb 8.x branches in the near future should depend on the
master branch in droolsjbpm-build-bootstrap.
<details>
<summary>
</summary>
* for an <b>upstream build</b> please add comment: <b>Jenkins run …
> Avoid future problems with pull request workflow config URL

- optaweb-vehicle-routing-backend/src/main/resources/org/optaweb/vehiclerouting/service/demo/belgium-cities.yaml
The Belgium data set became broken some time around March 2020.
I thought the Hasselt location became inaccessible because of movement
restrictions introduced in response to the pandemic. In any case, the
location is still inacessible and we need the built-in data set to work
out of the box. Therefore, making Hasselt accessible by moving it
further from the city center.
https://issues.redhat.com/browse/PLANNER-2360
<details>
<summary>
</summary>
* for a <b>full production downstream build</b> please …
> PLANNER-2360: Move Hasselt out of city center to fix Belgium data set

- optaweb-vehicle-routing-standalone/pom.xml
The tests are currently unstable or broken. The fix may require
a non-trivial effort. To make the CI stable, let's disable the tests for
now.
<details>
<summary>
</summary>
</details>
> Disable Cypress tests on the standalone module

- Jenkinsfile
Fix Jenkins build that started failing after integration tests were disabled in #461.
<details>
<summary>
</summary>
</details>
> Allow empty archive on Jenkins

- optaweb-vehicle-routing-backend/src/main/java/org/optaweb/vehiclerouting/plugin/planner/SolverManager.java
- optaweb-vehicle-routing-backend/src/test/java/org/optaweb/vehiclerouting/plugin/planner/SolverExceptionTest.java
https://issues.redhat.com/browse/PLANNER-2388
Improve error message to avoid confusion. It's inappropriate to use "impossible" for something that actually happens during test execution.
<details>
<summary>
</summary>
</details>
> PLANNER-2388: Improve solver error message

- optaweb-vehicle-routing-backend/src/main/java/org/optaweb/vehiclerouting/plugin/rest/RouteEventResource.java
<details>
<summary>
</summary>
</details>
> Avoid NPE when shutting down the backend and there is no SSE connection

- .github/workflows/pull_request.yml
According to the "df -h" output in the PR checks, the entire "Free disk space"
step frees up ~17 GB of disk space. Package cleanup, being part of it, frees ~4 GB,
but the enumeration of individual packages makes the CI brittle.
As an example, the CI has been failing recently in this step due to the inexistence of `heroku` package(s).
<details>
<summary>
</summary>
* for an <b>upstream build</b> …
> Remove package cleanup from GHA

- pom.xml
https://issues.redhat.com/browse/PLANNER-2389
https://github.com/kiegroup/optaplanner/pull/1254
https://github.com/kiegroup/optaplanner-quickstarts/pull/93
https://github.com/kiegroup/optaweb-employee-rostering/pull/602
https://github.com/kiegroup/optaweb-vehicle-routing/pull/471
<details>
<summary>
</summary>
</details>
> PLANNER-2389 Remove version overrides

- optaweb-vehicle-routing-backend/src/test/java/org/optaweb/vehiclerouting/plugin/planner/SolverIntegrationTest.java
- optaweb-vehicle-routing-standalone/src/main/resources/application.properties
<details>
<summary>
</summary>
</details>
> Disable flaky test, fix regression after Quarkus upgrade

- optaweb-vehicle-routing-backend/src/test/java/org/optaweb/vehiclerouting/plugin/planner/SolverIntegrationTest.java
- optaweb-vehicle-routing-standalone/src/main/resources/application.properties
There was a test failure in the release build due to a test that is marked as flaky on the master branch.
I am also cherry-picking [a fix](https://github.com/kiegroup/optaweb-vehicle-routing/commit/b58820123906bea6eb5a51269eefcf3c905e4b4c) that is missing on this branch.
<details>
<summary>
</summary>
</details>
> Increase timeout in a test

- .github/workflows/pull_request.yml
https://issues.redhat.com/browse/BXMSPROD-1363
- https://github.com/kiegroup/optaweb-employee-rostering/pull/639
- https://github.com/kiegroup/optaweb-vehicle-routing/pull/514
<details>
<summary>
</summary>
</details>
> BXMSPROD-1363 [master] build-chain definition and project-dependencies upgraded to v2.1

- .github/workflows/pull_request.yml
The build chain tool is not properly taken into account for excluded projects. https://github.com/kiegroup/github-action-build-chain/pull/160 solves the problem
related PR
- https://github.com/kiegroup/github-action-build-chain/pull/160
- https://github.com/kiegroup/optaweb-vehicle-routing/pull/527
- https://github.com/kiegroup/optaweb-employee-rostering/pull/654
- https://github.com/kiegroup/optaplanner/pull/1418
- https://github.com/kiegroup/optaweb-vehicle-routing/pull/528
- https://github.com/kiegroup/optaweb-employee-rostering/pull/655
<details>
<summary>
</summary>
* for a …
> BXMSPROD-1413 [master] [build-chain upgrade] exclude projects not taken into account

- .github/workflows/pull_request.yml
The build chain tool is not properly taken into account for excluded projects. https://github.com/kiegroup/github-action-build-chain/pull/160 solves the problem
related PR
- https://github.com/kiegroup/github-action-build-chain/pull/160
- https://github.com/kiegroup/optaweb-vehicle-routing/pull/527
- https://github.com/kiegroup/optaweb-employee-rostering/pull/654
- https://github.com/kiegroup/optaplanner/pull/1418
- https://github.com/kiegroup/optaweb-vehicle-routing/pull/528
- https://github.com/kiegroup/optaweb-employee-rostering/pull/655
<details>
<summary>
</summary>
* for a …
> BXMSPROD-1413 [7.x] [build-chain upgrade] exclude projects not taken into account

- optaweb-vehicle-routing-backend/src/main/java/org/optaweb/vehiclerouting/plugin/routing/RoutingConfig.java
- optaweb-vehicle-routing-backend/src/main/java/org/optaweb/vehiclerouting/plugin/routing/RoutingProperties.java
- optaweb-vehicle-routing-backend/src/main/java/org/optaweb/vehiclerouting/service/demo/DemoProperties.java
- optaweb-vehicle-routing-backend/src/main/java/org/optaweb/vehiclerouting/service/demo/RoutingProblemConfig.java
- optaweb-vehicle-routing-backend/src/main/java/org/optaweb/vehiclerouting/service/region/RegionProperties.java
- optaweb-vehicle-routing-backend/src/main/java/org/optaweb/vehiclerouting/service/region/RegionService.java
- optaweb-vehicle-routing-backend/src/test/java/org/optaweb/vehiclerouting/service/region/RegionPropertiesTest.java
- optaweb-vehicle-routing-backend/src/test/java/org/optaweb/vehiclerouting/service/region/RegionServiceTest.java
`@ConfingProperties` became deprecated in Quarkus 2.0.0.
SmallRye documentation:
https://smallrye.io/docs/smallrye-config/mapping/mapping.html
Do not merge before we upgrade to a Quarkus version that brings `smallrye-config` at least 2.4.0. Done: kiegroup/optaplanner/pull/1451.
We need https://github.com/smallrye/smallrye-config/pull/600 that fixes a problem with `.env` file containing for example `APP_DEMO_DATA_SET_DIR`.
<details>
<summary>
</summary>
* for a <b>full production downstream build</b> …
> Replace deprecated ConfigProperties with ConfigMapping

- .github/workflows/pull_request.yml
**Thank you for submitting this pull request**
**JIRA**: https://issues.redhat.com/browse/BXMSPROD-1475
**referenced Pull Requests**: 
* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1770
* https://github.com/kiegroup/kie-soup/pull/228
* https://github.com/kiegroup/droolsjbpm-knowledge/pull/549
* https://github.com/kiegroup/drools/pull/3835
* https://github.com/kiegroup/optaplanner/pull/1577
* https://github.com/kiegroup/lienzo-core/pull/152
* https://github.com/kiegroup/lienzo-tests/pull/126
* https://github.com/kiegroup/appformer/pull/1197
* https://github.com/kiegroup/kie-uberfire-extensions/pull/124
* https://github.com/kiegroup/jbpm/pull/2024
* https://github.com/kiegroup/kie-jpmml-integration/pull/65
* https://github.com/kiegroup/droolsjbpm-integration/pull/2607
* …
> [main] BXMSPROD-1475 force maven to 3.8.1

- .github/workflows/pull_request.yml
<details>
<summary>
</summary>
* for a <b>Quarkus LTS check</b> please add comment: <b>Jenkins run LTS</b>
* for a <b>specific Quarkus LTS check</b> please add comment: <b>Jenkins (re)run …
> PLANNER-2526 Introduce JDK 17

- optaweb-vehicle-routing-backend/src/main/resources/application.properties
This is needed for upgrading to Quarkus 2.3.0 where the datasource is
created more strictly and it fails in build time if the DATABASE_USER
property is not set.
<details>
<summary>
</summary>
* for a …
> Move PostgreSQL config to the postgres profile

- optaweb-vehicle-routing-backend/src/main/docker/Dockerfile.jvm
- optaweb-vehicle-routing-backend/src/main/docker/Dockerfile.legacy-jar
- optaweb-vehicle-routing-backend/src/main/docker/Dockerfile.native
- optaweb-vehicle-routing-backend/src/main/docker/Dockerfile.native-distroless
https://issues.redhat.com/browse/RHDM-1838
- #582
- #592
- #593
<details>
<summary>
</summary>
* for a <b>Quarkus LTS check</b> please add comment: <b>Jenkins run LTS</b>
* for a <b>specific Quarkus LTS …
> RHDM-1838: Fix runOnOpenShift.sh by regenerating Quarkus Dockerfiles

- optaweb-vehicle-routing-backend/src/main/docker/Dockerfile.jvm
- optaweb-vehicle-routing-backend/src/main/docker/Dockerfile.legacy-jar
- optaweb-vehicle-routing-backend/src/main/docker/Dockerfile.native
- optaweb-vehicle-routing-backend/src/main/docker/Dockerfile.native-distroless
https://issues.redhat.com/browse/RHDM-1838
- #582
- #592
- #593
<details>
<summary>
</summary>
* for a <b>Quarkus LTS check</b> please add comment: <b>Jenkins run LTS</b>
* for a <b>specific Quarkus LTS …
> [8.11.x] RHDM-1838: Fix runOnOpenShift.sh by regenerating Quarkus Dockerfiles

- .github/workflows/pull_request.yml
https://issues.redhat.com/browse/BXMSPROD-1542
I will propagate the change to drools, droolsjbpm-knowledge, and opta* projects as soon as we agree on the change
[main]
- https://github.com/kiegroup/drools/pull/4017
- https://github.com/kiegroup/optaplanner/pull/1672
- https://github.com/kiegroup/optaweb-employee-rostering/pull/718
- https://github.com/kiegroup/optaweb-vehicle-routing/pull/602
[8.14.x]
- https://github.com/kiegroup/drools/pull/4019
- https://github.com/kiegroup/optaplanner/pull/1674
- https://github.com/kiegroup/optaweb-employee-rostering/pull/720
- https://github.com/kiegroup/optaweb-vehicle-routing/pull/605
[8.11.x]
- https://github.com/kiegroup/optaweb-vehicle-routing/pull/603
- https://github.com/kiegroup/optaplanner/pull/1673
- …
> BXMSPROD-1542 definition-file eval expression

- .github/workflows/pull_request.yml
https://issues.redhat.com/browse/BXMSPROD-1542
- https://github.com/kiegroup/optaweb-vehicle-routing/pull/603
- https://github.com/kiegroup/optaweb-vehicle-routing/pull/602
I will propagate the change to drools, droolsjbpm-knowledge, and opta* projects as soon as we agree on the change
<details>
<summary>
</summary> …
> [8.11.x] BXMSPROD-1542 definition-file eval expression

- .ci/jenkins/dsl/jobs.groovy
- .github/pull_request_template.md
Signed-off-by: Lukáš Petrovický <lpetrovi@redhat.com>
<details>
<summary>
</summary> …
> PLANNER-2595 Disable native CI

- .github/workflows/pull_request.yml
This PR adds a step that fails if there are any uncommitted changes in the Git working tree of `optaweb-vehicle-routing` after running the Maven build. The goal is to detect PRs where changes to `package.json` in `optaweb-vehicle-routing-frontend` are made without reflecting that in `package-lock.json`.
The `package-lock.json` must be always perfectly in sync with `package.json` to:
- Ensure build stability (CI and other developers use exactly the same dependencies as the author who last updated `package.json`).
- Avoid merge conflicts on `pacakge-lock.json`.
<details>
<summary>
</summary>
Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any …
> [7.x] Add a check that fails if there are any uncommitted changes

- optaweb-vehicle-routing-backend/.gitignore
Ignoring files created (and ignored) on main makes it more comfortable
to switch between branches. Without ignoring main-ignored files also on
7.x, when you switch to 7.x, `git status` suddenly reports untracked
files, creating unnecessary noise.
- https://github.com/kiegroup/optaweb-vehicle-routing/pull/622
- https://github.com/kiegroup/optaweb-employee-rostering/pull/737
<details>
<summary>
</summary>
Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to handle cross …
> Ignore new files created on main

- optaweb-vehicle-routing-backend/src/test/java/org/optaweb/vehiclerouting/plugin/routing/GraphHopperRouterTest.java
- pom.xml
Trying to upgrade protobuf caused this exception
```
Caused by: java.lang.UnsupportedOperationException
at org.openstreetmap.osmosis.osmbinary.Fileformat$BlobHeader.dynamicMethod(Fileformat.java:1430)
at com.google.protobuf.GeneratedMessageLite.dynamicMethod(GeneratedMessageLite.java:256)
```
The problem is explained [here](https://discuss.graphhopper.com/t/failure-to-read-pbf-at-startup-not-supporting-message-info/5448/7) and I solved it also upgrading `graphhopper` to the latest stable version. As reported [here](https://github.com/graphhopper/graphhopper/blob/master/CHANGELOG.md#10-22-may-2020) this also required to change `PathWrapper` into `ResponsePath`.
> [DROOLS-6769] upgrade protobuf to version 3.17.3

- optaweb-vehicle-routing-backend/src/main/java/org/optaweb/vehiclerouting/plugin/planner/SolverManager.java
- optaweb-vehicle-routing-backend/src/main/java/org/optaweb/vehiclerouting/plugin/planner/change/AddVehicle.java
- optaweb-vehicle-routing-backend/src/main/java/org/optaweb/vehiclerouting/plugin/planner/change/AddVisit.java
- optaweb-vehicle-routing-backend/src/main/java/org/optaweb/vehiclerouting/plugin/planner/change/ChangeVehicleCapacity.java
- optaweb-vehicle-routing-backend/src/main/java/org/optaweb/vehiclerouting/plugin/planner/change/RemoveVehicle.java
- optaweb-vehicle-routing-backend/src/main/java/org/optaweb/vehiclerouting/plugin/planner/change/RemoveVisit.java
- optaweb-vehicle-routing-backend/src/main/java/org/optaweb/vehiclerouting/plugin/planner/change/package-info.java
- optaweb-vehicle-routing-backend/src/test/java/org/optaweb/vehiclerouting/plugin/planner/MockSolver.java
- optaweb-vehicle-routing-backend/src/test/java/org/optaweb/vehiclerouting/plugin/planner/SolverIntegrationTest.java
- optaweb-vehicle-routing-backend/src/test/java/org/optaweb/vehiclerouting/plugin/planner/SolverManagerTest.java
- optaweb-vehicle-routing-backend/src/test/java/org/optaweb/vehiclerouting/plugin/planner/change/AddVehicleTest.java
- optaweb-vehicle-routing-backend/src/test/java/org/optaweb/vehiclerouting/plugin/planner/change/AddVisitTest.java
- optaweb-vehicle-routing-backend/src/test/java/org/optaweb/vehiclerouting/plugin/planner/change/ChangeVehicleCapacityTest.java
- optaweb-vehicle-routing-backend/src/test/java/org/optaweb/vehiclerouting/plugin/planner/change/RemoveVehicleTest.java
- optaweb-vehicle-routing-backend/src/test/java/org/optaweb/vehiclerouting/plugin/planner/change/RemoveVisitTest.java
https://issues.redhat.com/browse/PLANNER-2541
https://github.com/kiegroup/optaplanner/pull/1703
https://github.com/kiegroup/optaplanner-quickstarts/pull/259
https://github.com/kiegroup/optaweb-vehicle-routing/pull/635
<details>
<summary>
</summary>
[build-chain …
> PLANNER-2541 Simplify ProblemFactChange interface

- .github/workflows/sonarcloud.yml
Copy-pasted from https://github.com/kiegroup/optaplanner/blob/fb2395c33ed9d6b63954e2a040429e494f835926/.github/workflows/sonarcloud.yml with some minor cleanup:
```diff
1,2c1,2
< # Runs the SonarCloud analysis of the optaplanner main branch after a PR is merged.
< name: OptaPlanner SonarCloud Analysis
---
> # Runs SonarCloud analysis of the main branch after a PR is merged.
> name: SonarCloud analysis
9a10
>       - 'CODEOWNERS'
10a12
>       - '.gitattributes'
13,14c15,18
<       - '*.txt'
<       - '.ci/**'      
---
>       - '**.txt'
>       - 'runOnOpenShift.sh'
>       - 'runLocally.sh'
>       - '.ci/**'
49c53
<         run: mvn -B --fail-at-end validate -Psonarcloud-analysis -Dsonar.projectKey=org.optaplanner:optaplanner -Dsonar.login=${{ env.SONARCLOUD_TOKEN }}
---
>         run: …
```
> PLANNER-2465: Run SonarCloud analysis after push to main

- optaweb-vehicle-routing-frontend/docker/default.conf
- optaweb-vehicle-routing-frontend/docker/nginx.conf
See commit descriptions for explanation.
@dupliaka I've tested this on locally in CRC. I do not expect thorough verification. A simple ack will do in this case.
<details>
<summary>
</summary>
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used on command line …
> Increase proxy read timeout for SSE endpoint to avoid frequent connection resets on OpenShift

- optaweb-vehicle-routing-backend/.dockerignore
- optaweb-vehicle-routing-backend/pom.xml
- optaweb-vehicle-routing-backend/src/main/docker/Dockerfile.jvm
- optaweb-vehicle-routing-backend/src/main/resources/application.properties
- optaweb-vehicle-routing-standalone/src/main/resources/application.properties
- runOnOpenShift.sh
1. Create two quarkus-maven-plugin executions that build quarkus-app-h2
and quarkus-app-postgresql. See
https://quarkus.io/guides/maven-tooling#maven-multi-build.
2. Add Dockerfile.jvm ARG that allows to choose from the two above.
3. By default, it builds an image with quarkus-app-h2. But
runOnOpenShift.sh uses the ARG to choose quarkus-app-postgresql.
https://issues.redhat.com/browse/PLANNER-2645
<details>
<summary>
</summary>
Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) …
> PLANNER-2645: Use PostgreSQL when running on OpenShift

- optaweb-vehicle-routing-backend/src/main/java/org/optaweb/vehiclerouting/plugin/websocket/WebSocketConfig.java
- pom.xml
https://issues.redhat.com/browse/RHPAM-4111
- https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1872
- https://github.com/kiegroup/droolsjbpm-integration/pull/2693
- https://github.com/kiegroup/optaweb-vehicle-routing/pull/641
- https://github.com/kiegroup/optaweb-employee-rostering/pull/755
<details>
<summary>
</summary>
Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to handle cross repository builds and be sure that we always use latest version of the code for …
> [7.x] RHPAM-4111: Update dependencies to match Spring Boot 2.4.9 and fix CORS configuration

- .mvn/wrapper/maven-wrapper.properties
https://issues.redhat.com/browse/KOGITO-6682
Related PRs:
- https://github.com/kiegroup/drools/pull/4174
- https://github.com/kiegroup/kogito-runtimes/pull/1962
- https://github.com/kiegroup/optaplanner/pull/1820
- https://github.com/kiegroup/optaweb-vehicle-routing/pull/647
- https://github.com/kiegroup/optaplanner-quickstarts/pull/277
- https://github.com/kiegroup/kogito-apps/pull/1227
- https://github.com/kiegroup/kogito-examples/pull/1109
> KOGITO-6682 Force maven version to 3.8.1+

- .ci/jenkins/dsl/jobs.groovy
- .ci/jenkins/scripts/update-version/git_stage_files.groovy
- .ci/jenkins/scripts/update-version/init.groovy
- .ci/jenkins/scripts/update-version/main.groovy
- .github/workflows/full-downstream.yml
- .github/workflows/pull_request.yml
- .github/workflows/sonarcloud.yml
- .mvn/wrapper/maven-wrapper.properties
Depends on https://github.com/kiegroup/kogito-pipelines/pull/388
I backported changes from `main` which are useful and removed drools references.
- https://github.com/kiegroup/kogito-pipelines/pull/388
- https://github.com/kiegroup/kogito-pipelines/pull/390
- https://github.com/kiegroup/kogito-runtimes/pull/2028
- https://github.com/kiegroup/optaplanner/pull/1850
- https://github.com/kiegroup/optaweb-vehicle-routing/pull/662
- https://github.com/kiegroup/optaweb-employee-rostering/pull/771
- https://github.com/kiegroup/optaplanner-quickstarts/pull/295
- https://github.com/kiegroup/kogito-apps/pull/1258
- https://github.com/kiegroup/kogito-examples/pull/1144
- https://github.com/kiegroup/kogito-images/pull/1126
- https://github.com/kiegroup/kogito-operator/pull/1139
> [1.13.x] Prepare branch for productization

- optaweb-vehicle-routing-backend/.dockerignore
- optaweb-vehicle-routing-backend/pom.xml
- optaweb-vehicle-routing-backend/src/main/docker/Dockerfile.jvm
- optaweb-vehicle-routing-backend/src/main/docker/Dockerfile.legacy-jar
- optaweb-vehicle-routing-backend/src/main/docker/Dockerfile.native
- optaweb-vehicle-routing-backend/src/main/docker/Dockerfile.native-distroless
- optaweb-vehicle-routing-backend/src/main/resources/application.properties
- optaweb-vehicle-routing-standalone/src/main/resources/application.properties
- runOnOpenShift.sh
https://issues.redhat.com/browse/RHPAM-4228
<details>
<summary>
</summary>
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used on command line locally or in Github Actions workflow(s), in case you need to change multiple repositories and send multiple dependent …
> [8.13.x] RHPAM-4228: Use PostgreSQL when running on OpenShift

- .github/pull_request_template.md
* https://github.com/kiegroup/optaplanner/pull/1889
* https://github.com/kiegroup/optaplanner-quickstarts/pull/312
* https://github.com/kiegroup/optaweb-employee-rostering/pull/781
* https://github.com/kiegroup/optaweb-vehicle-routing/pull/668
<details>
<summary>
</summary>
[build-chain …
> CI status webpage

- optaweb-vehicle-routing-backend/pom.xml
- optaweb-vehicle-routing-distribution/pom.xml
- optaweb-vehicle-routing-docs/pom.xml
- optaweb-vehicle-routing-frontend/pom.xml
- optaweb-vehicle-routing-standalone/pom.xml
- pom.xml
- https://github.com/kiegroup/drools/pull/4286
- https://github.com/kiegroup/optaplanner/pull/1907
- https://github.com/kiegroup/optaplanner-quickstarts/pull/316
- https://github.com/kiegroup/optaweb-employee-rostering/pull/784
- https://github.com/kiegroup/optaweb-vehicle-routing/pull/674
- https://github.com/kiegroup/kogito-apps/pull/1291
- https://github.com/kiegroup/kogito-examples/pull/1205
- https://github.com/kiegroup/kogito-runtimes/pull/2121
<details>
<summary>
</summary>
Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain …
> bumped up to next 8.20.0-SNAPSHOT

- optaweb-vehicle-routing-backend/src/main/resources/application-dev-cypress.properties
- optaweb-vehicle-routing-backend/src/main/resources/application-production.properties
- optaweb-vehicle-routing-backend/src/main/resources/application.properties
https://issues.redhat.com/browse/BXMSPROD-1673
* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1935
* https://github.com/kiegroup/optaplanner/pull/1910
* https://github.com/kiegroup/droolsjbpm-integration/pull/2759
* https://github.com/kiegroup/openshift-drools-hacep/pull/129
* https://github.com/kiegroup/optaweb-employee-rostering/pull/785
* https://github.com/kiegroup/optaweb-vehicle-routing/pull/675
<details>
<summary>
</summary>
Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain …
> BXMSPROD-1673 spring-webmvc/spring-framework 5.3.18. spring-boot to 2.6.6

- optaweb-vehicle-routing-backend/src/main/java/org/optaweb/vehiclerouting/plugin/websocket/WebSocketConfig.java
- optaweb-vehicle-routing-backend/src/main/resources/application-dev-cypress.properties
- optaweb-vehicle-routing-backend/src/main/resources/application-production.properties
- optaweb-vehicle-routing-backend/src/main/resources/application.properties
- optaweb-vehicle-routing-backend/src/test/java/org/optaweb/vehiclerouting/plugin/websocket/WebSocketErrorMessageSenderTest.java
- optaweb-vehicle-routing-backend/src/test/java/org/optaweb/vehiclerouting/service/error/ErrorListenerTest.java
- optaweb-vehicle-routing-backend/src/test/java/org/optaweb/vehiclerouting/service/location/LocationServiceTest.java
https://issues.redhat.com/browse/BXMSPROD-1673
**referenced Pull Requests**: _(please edit the URLs of referenced pullrequests if they exist)_
* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1939
* https://github.com/kiegroup/optaplanner/pull/1920
* https://github.com/kiegroup/droolsjbpm-integration/pull/2764
* https://github.com/kiegroup/openshift-drools-hacep/pull/128
* https://github.com/kiegroup/optaweb-employee-rostering/pull/786
* https://github.com/kiegroup/optaweb-vehicle-routing/pull/676
<details>
<summary>
</summary>
Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of …
> [7.59.x] BXMSPROD-1673 spring-webmvc/spring-framework 5.3.18. spring-boot to 2.6.6

- optaweb-vehicle-routing-backend/src/main/resources/application-dev-cypress.properties
- optaweb-vehicle-routing-backend/src/main/resources/application-production.properties
- optaweb-vehicle-routing-backend/src/main/resources/application.properties
https://issues.redhat.com/browse/BXMSPROD-1673
**referenced Pull Requests**:
* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1938
* https://github.com/kiegroup/optaplanner/pull/1916
* https://github.com/kiegroup/droolsjbpm-integration/pull/2760
* https://github.com/kiegroup/openshift-drools-hacep/pull/131
* https://github.com/kiegroup/optaweb-employee-rostering/pull/787
* https://github.com/kiegroup/optaweb-vehicle-routing/pull/677
<details>
<summary>
</summary>
Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain …
> [7.67.x] [BXMSPROD-1673] spring-webmvc/spring-framework 5.3.18. spring-boot to 2.6.6

- pom.xml
Overriding test dependencies only.
Keeping them aligned avoids future problems like in 718cd573b915f6de1fd04124025500f81e4148ae.
See https://mvnrepository.com/artifact/org.springframework.boot/spring-boot-starter-test/2.6.6.
<details>
<summary>
</summary>
[build-chain …
> Keep JUnit and Mockito versions aligned with Spring Boot 2.6.6

- build/release/upload_distribution.sh
Updates the upload server for docs and distribution.
<details>
<summary>
</summary> …
> [8.20.x] Change the upload server

- build/release/upload_distribution.sh
Updates the upload server for docs and distribution.
<details>
<summary>
</summary> …
> Change the upload server

- pom.xml
https://issues.redhat.com/browse/PLANNER-2605
- https://github.com/kiegroup/optaweb-vehicle-routing/pull/695
- https://github.com/kiegroup/optaweb-employee-rostering/pull/811
<details>
<summary>
</summary>
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used on …
> PLANNER-2605 Update frontend-maven-plugin, node, and npm

- .ci/jenkins/dsl/Jenkinsfile.seed
https://issues.redhat.com/browse/KOGITO-7356
Related:
- https://github.com/kiegroup/kogito-pipelines/pull/484
- https://github.com/kiegroup/drools/pull/4446
- https://github.com/kiegroup/kogito-runtimes/pull/2252
- https://github.com/kiegroup/kogito-apps/pull/1375
- https://github.com/kiegroup/kogito-examples/pull/1285
- https://github.com/kiegroup/kogito-images/pull/1275
- https://github.com/kiegroup/kogito-operator/pull/1204
- https://github.com/kiegroup/optaplanner/pull/2023
- https://github.com/kiegroup/optaweb-vehicle-routing/pull/708
- https://github.com/kiegroup/optaweb-employee-rostering/pull/826
- https://github.com/kiegroup/optaplanner-quickstarts/pull/352
> [8.13.x] KOGITO-7356 Do not use master node in pipelines

- .ci/jenkins/dsl/Jenkinsfile.seed
https://issues.redhat.com/browse/KOGITO-7356
Related:
- https://github.com/kiegroup/kogito-pipelines/pull/485
- https://github.com/kiegroup/kogito-runtimes/pull/2255
- https://github.com/kiegroup/kogito-examples/pull/1286
- https://github.com/kiegroup/kogito-images/pull/1276
- https://github.com/kiegroup/kogito-operator/pull/1205
- https://github.com/kiegroup/optaplanner/pull/2025
- https://github.com/kiegroup/optaweb-vehicle-routing/pull/709
- https://github.com/kiegroup/optaweb-employee-rostering/pull/827
- https://github.com/kiegroup/optaplanner-quickstarts/pull/353
> [8.13.x-blue] KOGITO-7356 Do not use master node in pipelines

- optaweb-vehicle-routing-standalone/pom.xml
https://issues.redhat.com/browse/PLANNER-2743
<details>
<summary>
</summary>
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used on command line locally or in Github Actions workflow(s), in case you need to change multiple repositories and send multiple dependent …
> PLANNER-2743: Use fully qualified Cypress image name

- .ci/jenkins/dsl/test.sh
- .github/workflows/jenkins-tests-PR.yml
<details>
<summary>
</summary> …
> [PLANNER-2728] Extract optaplanner release from Kogito

- .ci/jenkins/Jenkinsfile.init-branch
- .ci/jenkins/dsl/jobs.groovy
https://issues.redhat.com/browse/KOGITO-7786
Example init commit: https://github.com/radtriste/optaweb-vehicle-routing/commit/18815c0745e5a37e6b06607bf451f7eb24ad2e84
Related PRs:
- https://github.com/kiegroup/optaplanner/pull/2144
- https://github.com/kiegroup/optaweb-vehicle-routing/pull/746
- https://github.com/kiegroup/optaplanner-quickstarts/pull/394
<details>
<summary>
</summary>
Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to handle cross repository builds and be …
> KOGITO-7786 Setup init-branch jobs

- pom.xml
This version support splitting multiple non proxy hosts
See: https://github.com/eirslett/frontend-maven-plugin/blob/frontend-plugins-1.11.3/frontend-plugin-core/src/main/java/com/github/eirslett/maven/plugins/frontend/lib/NpmRunner.java#L44
<details>
<summary>
</summary>
[build-chain …
> update frontend-maven-plugin to version 1.11.3

- .github/workflows/pull_request.yml
<details>
<summary>
</summary> …
> PLANNER-2807 Use JDK 19 in Github Actions

- .ci/jenkins/dsl/jobs.groovy
- .github/pull_request_template.md
- remove Mandrel LTS check as no native on optaweb
https://issues.redhat.com/browse/PLANNER-2822
- https://github.com/kiegroup/optaplanner/pull/2217
- https://github.com/kiegroup/optaweb-vehicle-routing/pull/759
- https://github.com/kiegroup/optaplanner-quickstarts/pull/413
- https://github.com/kiegroup/kogito-pipelines/pull/641
<details>
<summary>
</summary>
Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to handle cross repository builds and be sure that we always use …
> PLANNER-2822 Remove Mandrel LTS check

- .ci/jenkins/Jenkinsfile.setup-branch
- .ci/jenkins/dsl/jobs.groovy
https://issues.redhat.com/browse/PLANNER-2829
- https://github.com/kiegroup/kogito-pipelines/pull/658
- https://github.com/kiegroup/optaplanner/pull/2255
- https://github.com/kiegroup/optaweb-vehicle-routing/pull/774
- https://github.com/kiegroup/optaplanner-quickstarts/pull/437
<details>
<summary>
</summary> …
> PLANNER-2829 Init branch becomes Setup branch

- .github/workflows/rhbop_productized_pull_request.yml
- https://issues.redhat.com/browse/BXMSPROD-1861
- https://github.com/kiegroup/optaplanner/pull/2275
- https://github.com/kiegroup/optaplanner-quickstarts/pull/446
- https://github.com/kiegroup/optaweb-vehicle-routing/pull/790
- https://github.com/kiegroup/drools/pull/4795
Added productized build checks for RHBOP optaplanner product.
<details>
<summary>
</summary>
Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to handle cross repository builds and be sure that we always use …
> [BXMSPROD-1861] Added PR CI workflow for productized rhbop

- .github/workflows/rhbop_productized_pull_request.yml
- https://issues.redhat.com/browse/BXMSPROD-1861
- https://github.com/kiegroup/optaweb-vehicle-routing/pull/790 (main)
- https://github.com/kiegroup/optaplanner/pull/2294
- https://github.com/kiegroup/optaplanner-quickstarts/pull/448
- https://github.com/kiegroup/optaweb-vehicle-routing/pull/791
- https://github.com/kiegroup/drools/pull/4796
Backport on `8.29.x` branch
<details>
<summary>
</summary>
Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to handle cross repository …
> [8.29.x] [BXMSPROD-1861] Added PR CI workflow for productized rhbop

- .github/workflows/full-downstream.yml
- .github/workflows/pull_request.yml
to main optaplanner repository
https://issues.redhat.com/browse/PLANNER-2868
Related:
- https://github.com/kiegroup/kogito-pipelines/pull/720
- https://github.com/kiegroup/optaplanner/pull/2388
- https://github.com/kiegroup/optaweb-vehicle-routing/pull/821
- https://github.com/kiegroup/optaplanner-quickstarts/pull/462
> PLANNER-2868 Move build-chain config

- .github/workflows/full-downstream.yml
- .github/workflows/pull_request.yml
- .github/workflows/rhbop_productized_pull_request.yml
https://issues.redhat.com/browse/PLANNER-2892
Related:
- https://github.com/kiegroup/optaplanner/pull/2530
- https://github.com/kiegroup/optaweb-vehicle-routing/pull/840
- https://github.com/kiegroup/optaplanner-quickstarts/pull/497
> PLANNER-2892 Update default Maven to 3.8.7

- .github/workflows/full-downstream.yml
- .github/workflows/pull_request.yml
- .github/workflows/rhbop_productized_pull_request.yml
Synchronize other workflows with sonarcloud.yml, which seems most accurate.
- Closes #540.
<details>
<summary>
</summary>
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used on command line locally or in Github Actions workflow(s), in case you need to change …
> Update paths-ignore of GitHub Actions workflows

- optaweb-vehicle-routing-frontend/src/store/websocket/operations.ts
- optaweb-vehicle-routing-frontend/src/websocket/WebSocketClient.test.ts
- optaweb-vehicle-routing-frontend/src/websocket/WebSocketClient.ts
https://issues.redhat.com/browse/PLANNER-2396
<details>
<summary>
</summary>
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used on command line locally or in Github Actions workflow(s), in case you need to change multiple repositories and send multiple dependent …
> PLANNER-2396 Reconnect EventSource when backend restarts

- optaweb-vehicle-routing-backend/pom.xml
It is not possible to use Javadoc plugin with Quarkus in its current form.
The issue comes with [quarkus-hibernate-orm-panache](https://github.com/kiegroup/optaweb-vehicle-routing/blob/main/optaweb-vehicle-routing-backend/pom.xml#L37) and produce the following error when building javadoc:
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-javadoc-plugin:3.5.0:jar (build-javadoc-jar) on project optaweb-vehicle-routing-backend: Execution build-javadoc-jar of goal org.apache.maven.plugins:maven-javadoc-plugin:3.5.0:jar failed: Unable to derive module descriptor for /home/jenkins/.m2/repository/org/jboss/spec/javax/resource/jboss-connector-api_1.7_spec/1.0.0.Final/jboss-connector-api_1.7_spec-1.0.0.Final.jar: jboss.connector.api.1.7.spec: Invalid module name: '1' is not a Java …
```
> Disable javadoc on Quarkus
